/* Autogenerated by /usr/bin/halcompile on Sat Nov 29 14:44:24 2025 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:PoKeysController:");
MODULE_INFO(linuxcnc, "pin:machine_estop:bit:0:out:Machine is in E-Stop condition:false:None");
MODULE_INFO(linuxcnc, "pin:machine_is_on:bit:0:in:Machine should be enabled:false:None");
MODULE_INFO(linuxcnc, "pin:io.input_pin.#:bit:5:out:Digital input pins:None:None");
MODULE_INFO(linuxcnc, "pin:io.output_pin.#:bit:5:in:Digital output pins:None:None");
MODULE_INFO(linuxcnc, "pin:io.solid_state_relay.#:bit:2:in:Solid state relays:None:None");
MODULE_INFO(linuxcnc, "pin:io.relay.#:bit:2:in:Relays:None:None");
MODULE_INFO(linuxcnc, "pin:io.open_collector.#:bit:4:in:Open collector digital outputs:None:None");
MODULE_INFO(linuxcnc, "pin:io.pwm_pin.#:float:6:in:PWM pins, valid values from 0.0 - 100.0 percent duty cycle:None:None");
MODULE_INFO(linuxcnc, "pin:motion.started:bit:0:in:Motion is being streamed:false:None");
MODULE_INFO(linuxcnc, "pin:motion.override_limit.#:bit:6:in:Limit switch override. Any pin set overrides globally on PoKeys:None:None");
MODULE_INFO(linuxcnc, "pin:axis.#.position_feedback:float:3:out:Position in machine units:None:None");
MODULE_INFO(linuxcnc, "pin:axis.#.limit_positive:bit:3:out:Positive limit switches:None:None");
MODULE_INFO(linuxcnc, "pin:axis.#.limit_negative:bit:3:out:Negative limit switches:None:None");
MODULE_INFO(linuxcnc, "pin:axis.#.home:bit:3:out:Home switches:None:None");
MODULE_INFO(linuxcnc, "param:internal_state:s32:0:rw:Current component state:-1:None");
MODULE_INFO(linuxcnc, "param:device_serial:u32:0:rw:PoKeys Device Serial:0:None");
MODULE_INFO(linuxcnc, "param:log_level:s32:0:rw:log level (DEBUG):-1:None");
MODULE_INFO(linuxcnc, "param:axis.#.step_scale:float:3:rw:1 machine unit equals x pulses:None:None");
MODULE_INFO(linuxcnc, "param:io.input_pin_number.#:s32:5:rw:Digital input pin mapping, index 1 based:None:None");
MODULE_INFO(linuxcnc, "param:io.output_pin_number.#:s32:5:rw:Digital output pin mapping, index 1 based:None:None");
MODULE_INFO(linuxcnc, "param:io.pwm_pin_number.#:s32:6:rw:PWM channel pin mapping, index 1 based:None:None");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_INFO(linuxcnc, "author:T.Frei");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_bit_t *machine_estop;
    hal_bit_t *machine_is_on;
    hal_bit_t *io_input_pin[5];
    hal_bit_t *io_output_pin[5];
    hal_bit_t *io_solid_state_relay[2];
    hal_bit_t *io_relay[2];
    hal_bit_t *io_open_collector[4];
    hal_float_t *io_pwm_pin[6];
    hal_bit_t *motion_started;
    hal_bit_t *motion_override_limit[6];
    hal_float_t *axis_position_feedback[3];
    hal_bit_t *axis_limit_positive[3];
    hal_bit_t *axis_limit_negative[3];
    hal_bit_t *axis_home[3];
    hal_s32_t internal_state;
    hal_u32_t device_serial;
    hal_s32_t log_level;
    hal_float_t axis_step_scale[3];
    hal_s32_t io_input_pin_number[5];
    hal_s32_t io_output_pin_number[5];
    hal_s32_t io_pwm_pin_number[6];
};
#include <stdlib.h>
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    int r = 0;
    int j = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_bit_newf(HAL_OUT, &(inst->machine_estop), comp_id,
        "%s.machine-estop", prefix);
    if(r != 0) return r;
    *(inst->machine_estop) = false;
    r = hal_pin_bit_newf(HAL_IN, &(inst->machine_is_on), comp_id,
        "%s.machine-is-on", prefix);
    if(r != 0) return r;
    *(inst->machine_is_on) = false;
    for(j=0; j < (5); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->io_input_pin[j]), comp_id,
            "%s.io.input-pin.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (5); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->io_output_pin[j]), comp_id,
            "%s.io.output-pin.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (2); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->io_solid_state_relay[j]), comp_id,
            "%s.io.solid-state-relay.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (2); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->io_relay[j]), comp_id,
            "%s.io.relay.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (4); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->io_open_collector[j]), comp_id,
            "%s.io.open-collector.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (6); j++) {
        r = hal_pin_float_newf(HAL_IN, &(inst->io_pwm_pin[j]), comp_id,
            "%s.io.pwm-pin.%01d", prefix, j);
        if(r != 0) return r;
    }
    r = hal_pin_bit_newf(HAL_IN, &(inst->motion_started), comp_id,
        "%s.motion.started", prefix);
    if(r != 0) return r;
    *(inst->motion_started) = false;
    for(j=0; j < (6); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->motion_override_limit[j]), comp_id,
            "%s.motion.override-limit.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (3); j++) {
        r = hal_pin_float_newf(HAL_OUT, &(inst->axis_position_feedback[j]), comp_id,
            "%s.axis.%01d.position-feedback", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (3); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->axis_limit_positive[j]), comp_id,
            "%s.axis.%01d.limit-positive", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (3); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->axis_limit_negative[j]), comp_id,
            "%s.axis.%01d.limit-negative", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (3); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->axis_home[j]), comp_id,
            "%s.axis.%01d.home", prefix, j);
        if(r != 0) return r;
    }
    r = hal_param_s32_newf(HAL_RW, &(inst->internal_state), comp_id,
        "%s.internal-state", prefix);
    inst->internal_state = -1;
    if(r != 0) return r;
    r = hal_param_u32_newf(HAL_RW, &(inst->device_serial), comp_id,
        "%s.device-serial", prefix);
    inst->device_serial = 0;
    if(r != 0) return r;
    r = hal_param_s32_newf(HAL_RW, &(inst->log_level), comp_id,
        "%s.log-level", prefix);
    inst->log_level = -1;
    if(r != 0) return r;
    for(j=0; j < (3); j++) {
        r = hal_param_float_newf(HAL_RW, &(inst->axis_step_scale[j]), comp_id,
            "%s.axis.%01d.step-scale", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (5); j++) {
        r = hal_param_s32_newf(HAL_RW, &(inst->io_input_pin_number[j]), comp_id,
            "%s.io.input-pin-number.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (5); j++) {
        r = hal_param_s32_newf(HAL_RW, &(inst->io_output_pin_number[j]), comp_id,
            "%s.io.output-pin-number.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (6); j++) {
        r = hal_param_s32_newf(HAL_RW, &(inst->io_pwm_pin_number[j]), comp_id,
            "%s.io.pwm-pin-number.%01d", prefix, j);
        if(r != 0) return r;
    }
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
char *names[16] = {0,};
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("PoKeysController");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "PoKeysController.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        int max_names = sizeof(names)/sizeof(names[0]);
        for(i=0; (i < max_names) && names[i]; i++) {
            if (strlen(names[i]) < 1) {
                rtapi_print_msg(RTAPI_MSG_ERR, "names[%d] is invalid (empty string)\n", i);
                r = -EINVAL;
                break;
            }
            r = export(names[i], i);
            if(r != 0) break;
       }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}
static void user_mainloop(void);

int __comp_parse_count(int *argc, char **argv) {
    int i;
    for (i = 0; i < *argc; i ++) {
        if (strncmp(argv[i], "count=", 6) == 0) {
            errno = 0;
            count = strtoul(&argv[i][6], NULL, 0);
            for (; i+1 < *argc; i ++) {
                argv[i] = argv[i+1];
            }
            argv[i] = NULL;
            (*argc)--;
            if (errno == 0) {
                return 1;
            }
        }
    }
    return 0;
}


int __comp_parse_names(int *argc, char **argv) {
    int i;
    for (i = 0; i < *argc; i ++) {
        if (strncmp(argv[i], "names=", 6) == 0) {
            char *p = &argv[i][6];
            int j;
            for (; i+1 < *argc; i ++) {
                argv[i] = argv[i+1];
            }
            argv[i] = NULL;
            (*argc)--;
            for (j = 0; j < 16; j ++) {
                names[j] = strtok(p, ",");
                p = NULL;
                if (names[j] == NULL) {
                    return 1;
                }
            }
            return 1;
        }
    }
    return 0;
}

int argc=0; char **argv=0;
int main(int argc_, char **argv_) {
    argc = argc_; argv = argv_;
    int found_count, found_names;
    found_count = __comp_parse_count(&argc, argv);
    found_names = __comp_parse_names(&argc, argv);
    if (found_count && found_names) {
        rtapi_print_msg(RTAPI_MSG_ERR, "count= and names= are mutually exclusive\n");
        return 1;
    }

    if(rtapi_app_main() < 0) return 1;
    user_mainloop();
    rtapi_app_exit();
    return 0;
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef machine_estop
#define machine_estop (*__comp_inst->machine_estop)
#undef machine_is_on
#define machine_is_on (0+*__comp_inst->machine_is_on)
#undef io_input_pin
#define io_input_pin(i) (*(__comp_inst->io_input_pin[i]))
#undef io_output_pin
#define io_output_pin(i) (0+*(__comp_inst->io_output_pin[i]))
#undef io_solid_state_relay
#define io_solid_state_relay(i) (0+*(__comp_inst->io_solid_state_relay[i]))
#undef io_relay
#define io_relay(i) (0+*(__comp_inst->io_relay[i]))
#undef io_open_collector
#define io_open_collector(i) (0+*(__comp_inst->io_open_collector[i]))
#undef io_pwm_pin
#define io_pwm_pin(i) (0+*(__comp_inst->io_pwm_pin[i]))
#undef motion_started
#define motion_started (0+*__comp_inst->motion_started)
#undef motion_override_limit
#define motion_override_limit(i) (0+*(__comp_inst->motion_override_limit[i]))
#undef axis_position_feedback
#define axis_position_feedback(i) (*(__comp_inst->axis_position_feedback[i]))
#undef axis_limit_positive
#define axis_limit_positive(i) (*(__comp_inst->axis_limit_positive[i]))
#undef axis_limit_negative
#define axis_limit_negative(i) (*(__comp_inst->axis_limit_negative[i]))
#undef axis_home
#define axis_home(i) (*(__comp_inst->axis_home[i]))
#undef internal_state
#define internal_state (__comp_inst->internal_state)
#undef device_serial
#define device_serial (__comp_inst->device_serial)
#undef log_level
#define log_level (__comp_inst->log_level)
#undef axis_step_scale
#define axis_step_scale(i) (__comp_inst->axis_step_scale[i])
#undef io_input_pin_number
#define io_input_pin_number(i) (__comp_inst->io_input_pin_number[i])
#undef io_output_pin_number
#define io_output_pin_number(i) (__comp_inst->io_output_pin_number[i])
#undef io_pwm_pin_number
#define io_pwm_pin_number(i) (__comp_inst->io_pwm_pin_number[i])
#undef FOR_ALL_INSTS
#define FOR_ALL_INSTS() struct __comp_state *__comp_inst; for(__comp_inst = __comp_first_inst; __comp_inst; __comp_inst = __comp_inst->_next)


#line 37 "./scripts/../source/template/PoKeysController.comp"
// ------------------------------------
// Empty template Loop
// ------------------------------------
void user_mainloop(void) {
    FOR_ALL_INSTS() {
        rtapi_print_msg(RTAPI_MSG_DBG, "Empty\n");
    }
}

static int __comp_get_data_size(void) { return 0; }
