component PoKeysHoming;

pin in signed request = 0;
pin out signed response = 0;

option homemod yes;

license "GPL"; // indicates GPL v2 or later
author "T.Frei";
;;
#include <motion.h>
#include <homing.h>

// data for per-joint homing-specific hal pins:
typedef struct {
    hal_bit_t* home_sw;      // home switch input
    hal_bit_t* homing;       // joint is homing
    hal_bit_t* homed;        // joint was homed
    hal_bit_t* index_enable; // motmod sets: request reset on index. encoder clears: index arrived
    hal_s32_t* home_state;   // homing state machine state
} joint_hal_data_t;

typedef struct {
    uint sequence;
    double offset;
} joint_param_data_t;

typedef struct {
    joint_hal_data_t joint[8]; // max 8 axis in PoKeys
    joint_param_data_t parameter[8];
} all_joints_home_data_t;

static emcmot_joint_t* _joint_emc_data;
static all_joints_home_data_t* _joint_home_data = 0;

static int makepins(int id, int njoints) {
    // home_pins needed to work with configs expecting them:
    int jno;
    int retval;
    joint_hal_data_t *addr;

    _joint_home_data = hal_malloc(sizeof(all_joints_home_data_t));
    if (_joint_home_data == 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "HOMING: all_joints_home_data_t malloc failed\n");
        return -1;
    }

    retval = 0;
    for (jno = 0; jno < njoints; jno++) {
        addr = &(_joint_home_data->joint[jno]);

        retval += hal_pin_bit_newf(HAL_IN, &(addr->home_sw), id, "joint.%d.home-sw-in", jno);
        retval += hal_pin_bit_newf(HAL_OUT, &(addr->homing), id, "joint.%d.homing", jno);
        retval += hal_pin_bit_newf(HAL_OUT, &(addr->homed), id, "joint.%d.homed", jno);
        retval += hal_pin_s32_newf(HAL_OUT, &(addr->home_state), id, "joint.%d.home-state", jno);
        retval += hal_pin_bit_newf(HAL_IO, &(addr->index_enable), id, "joint.%d.index-enable", jno);
    }

    return retval;
}

// All (skeleton) functions required for homing api follow:
void homeMotFunctions(void(*pSetRotaryUnlock)(int,int), int (*pGetRotaryIsUnlocked)(int)) {
    (void)pSetRotaryUnlock;
    (void)pGetRotaryIsUnlocked;
    return;
}

// ------------------------------------
// one-time initialization (return 0 if ok):
// ------------------------------------
int homing_init(int id,
                double servo_period,
                int n_joints,
                int n_extrajoints,
                emcmot_joint_t* pjoints) {
    (void)servo_period;
    (void)n_extrajoints;
    _joint_emc_data = pjoints;
    return makepins(id, n_joints);
}

// ------------------------------------
// 'do_homing()' looks at the home_state field of each joint struct
//  to decide what, if anything, needs to be done related to homing
//  the joint.  Homing is implemented as a state machine, the exact
//  sequence of states depends on the machine configuration.  It
//  can be as simple as immediately setting the current position to
//  zero, or a it can be a multi-step process (find switch, set
//  approximate zero, back off switch, find index, set final zero,
//  rapid to home position), or anywhere in between.
//  return 1 if allhomed
// ------------------------------------
bool do_homing(void) {
    return true;
}

// ------------------------------------
// return true if all active joints are homed
// ------------------------------------
bool get_allhomed() {
    emcmot_joint_t joint;

    for (int i = 0; i < 8; i++) {
        if ((_joint_emc_data[i]->flag & EMCMOT_JOINT_ACTIVE_BIT) == false) {
            continue;
        }

        if (*(_joint_home_data->joint[i].homed) == false) {
            return false;
        }
    }

    return true;
}

bool get_homed(int jno) {
    return _joint_home_data->joint[jno].homed;
}

bool get_home_is_idle(int jno) {
    (void)jno;
    return true;
}

bool get_home_is_synchronized(int jno) {
    (void)jno;
    return false;
}

bool get_home_needs_unlock_first(int jno) {
    (void)jno;
    return false;
}

int get_home_sequence(int jno) {
    return _joint_home_data->parameter[jno].sequence;
}

bool get_homing(int jno) {
    (void)jno;
    return false;
}

bool get_homing_at_index_search_wait(int jno) {
    (void)jno;
    return false;
}

bool get_homing_is_active() {
    return false;
}

bool get_index_enable(int jno) {
    (void)jno;
    return false;
}

void read_homing_in_pins(int njoints) {
    (void)njoints;
    return;
}

// EMCMOT_JOINT_HOME message
// Negative joint_num specifies homeall
void do_home_joint(int jno) {
    /*if (jno == -1) {
        H[0].homed = 0; // ensure at least one unhomed
        do_home_all();
    } else {
        do_home_one_joint(jno); // apply rules if home_sequence negative
    }*/
}

void set_unhomed(int jno, motion_state_t motstate) {
    (void)jno;
    (void)motstate;
    return;
}

void do_cancel_homing(int jno) {
    (void)jno;
    return;
}

void set_joint_homing_params(int jno,
                             double offset,
                             double home,
                             double home_final_vel,
                             double home_search_vel,
                             double home_latch_vel,
                             int home_flags,
                             int home_sequence,
                             bool volatile_home) {
    (void)home;
    (void)home_final_vel;
    (void)home_search_vel;
    (void)home_latch_vel;
    (void)home_flags;
    (void)volatile_home;

    _joint_home_data->parameter[jno].sequence = home_sequence;
    _joint_home_data->parameter[jno].offset = offset;
}

void update_joint_homing_params(int jno,
                                double offset,
                                double home,
                                int home_sequence) {
    (void)home;

    _joint_home_data->parameter[jno].sequence = home_sequence;
    _joint_home_data->parameter[jno].offset = offset;
}

void write_homing_out_pins(int njoints) {
    (void)njoints;
    return;
}

EXPORT_SYMBOL(homeMotFunctions);

EXPORT_SYMBOL(homing_init);
EXPORT_SYMBOL(do_homing);
EXPORT_SYMBOL(get_allhomed);
EXPORT_SYMBOL(get_homed);
EXPORT_SYMBOL(get_home_is_idle);
EXPORT_SYMBOL(get_home_is_synchronized);
EXPORT_SYMBOL(get_home_needs_unlock_first);
EXPORT_SYMBOL(get_home_sequence);
EXPORT_SYMBOL(get_homing);
EXPORT_SYMBOL(get_homing_at_index_search_wait);
EXPORT_SYMBOL(get_homing_is_active);
EXPORT_SYMBOL(get_index_enable);
EXPORT_SYMBOL(read_homing_in_pins);
EXPORT_SYMBOL(do_home_joint);
EXPORT_SYMBOL(do_cancel_homing);
EXPORT_SYMBOL(set_unhomed);
EXPORT_SYMBOL(set_joint_homing_params);
EXPORT_SYMBOL(update_joint_homing_params);
EXPORT_SYMBOL(write_homing_out_pins);
