/* Header mostly autogenerated by /usr/bin/halcompile, re-rerun --precompile PoKeysControllerPins.comp */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

// Component imports
#include <PoKeysLib.h>      // For PoKeys communication
#include <time.h>           // For clock_gettime()
#include <unistd.h>         // For struct useconds_t

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:PoKeysController:");
MODULE_INFO(linuxcnc, "pin:machine_estop:bit:0:out:Machine is in E-Stop condition:false:None");
MODULE_INFO(linuxcnc, "pin:machine_is_on:bit:0:in:Machine should be enabled:false:None");
MODULE_INFO(linuxcnc, "pin:io.input_pin.#:bit:5:out:Digital input pins:None:None");
MODULE_INFO(linuxcnc, "pin:io.output_pin.#:bit:5:in:Digital output pins:None:None");
MODULE_INFO(linuxcnc, "pin:io.solid_state_relay.#:bit:2:in:Solid state relays:None:None");
MODULE_INFO(linuxcnc, "pin:io.relay.#:bit:2:in:Relays:None:None");
MODULE_INFO(linuxcnc, "pin:io.open_collector.#:bit:4:in:Open collector digital outputs:None:None");
MODULE_INFO(linuxcnc, "pin:io.pwm_pin.#:float:6:in:PWM pins, valid values from 0.0 - 100.0 percent duty cycle:None:None");
MODULE_INFO(linuxcnc, "pin:motion.started:bit:0:in:Motion is being streamed:false:None");
MODULE_INFO(linuxcnc, "pin:motion.override_limit.#:bit:6:in:Limit switch override. Any pin set overrides globally on PoKeys:None:None");
MODULE_INFO(linuxcnc, "pin:axis.#.position_feedback:float:3:out:Position in machine units:None:None");
MODULE_INFO(linuxcnc, "pin:axis.#.limit_positive:bit:3:out:Positive limit switches:None:None");
MODULE_INFO(linuxcnc, "pin:axis.#.limit_negative:bit:3:out:Negative limit switches:None:None");
MODULE_INFO(linuxcnc, "pin:axis.#.home:bit:3:out:Home switches:None:None");
MODULE_INFO(linuxcnc, "param:internal_state:s32:0:rw:Current component state:-1:None");
MODULE_INFO(linuxcnc, "param:device_serial:u32:0:rw:PoKeys Device Serial:0:None");
MODULE_INFO(linuxcnc, "param:log_level:s32:0:rw:log level (DEBUG):-1:None");
MODULE_INFO(linuxcnc, "param:axis.#.step_scale:float:3:rw:1 machine unit equals x pulses:None:None");
MODULE_INFO(linuxcnc, "param:io.input_pin_number.#:s32:5:rw:Digital input pin mapping, index 1 based:None:None");
MODULE_INFO(linuxcnc, "param:io.output_pin_number.#:s32:5:rw:Digital output pin mapping, index 1 based:None:None");
MODULE_INFO(linuxcnc, "param:io.pwm_pin_number.#:s32:6:rw:PWM channel pin mapping, index 1 based:None:None");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_INFO(linuxcnc, "author:T.Frei");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state* _next;
    hal_bit_t* machine_estop;
    hal_bit_t* machine_is_on;
    hal_bit_t* io_input_pin[5];
    hal_bit_t* io_output_pin[5];
    hal_bit_t* io_solid_state_relay[2];
    hal_bit_t* io_relay[2];
    hal_bit_t* io_open_collector[4];
    hal_float_t* io_pwm_pin[6];
    hal_bit_t* motion_started;
    hal_bit_t* motion_override_limit[6];
    hal_float_t* axis_position_feedback[3];
    hal_bit_t* axis_limit_positive[3];
    hal_bit_t* axis_limit_negative[3];
    hal_bit_t* axis_home[3];
    hal_s32_t internal_state;
    hal_u32_t device_serial;
    hal_s32_t log_level;
    hal_float_t axis_step_scale[3];
    hal_s32_t io_input_pin_number[5];
    hal_s32_t io_output_pin_number[5];
    hal_s32_t io_pwm_pin_number[6];
    sPoKeysDevice* device;
};

#include <stdlib.h>
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    int r = 0;
    int j = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_bit_newf(HAL_OUT, &(inst->machine_estop), comp_id,
        "%s.machine-estop", prefix);
    if(r != 0) return r;
    *(inst->machine_estop) = false;
    r = hal_pin_bit_newf(HAL_IN, &(inst->machine_is_on), comp_id,
        "%s.machine-is-on", prefix);
    if(r != 0) return r;
    *(inst->machine_is_on) = false;
    for(j=0; j < (5); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->io_input_pin[j]), comp_id,
            "%s.io.input-pin.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (5); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->io_output_pin[j]), comp_id,
            "%s.io.output-pin.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (2); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->io_solid_state_relay[j]), comp_id,
            "%s.io.solid-state-relay.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (2); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->io_relay[j]), comp_id,
            "%s.io.relay.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (4); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->io_open_collector[j]), comp_id,
            "%s.io.open-collector.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (6); j++) {
        r = hal_pin_float_newf(HAL_IN, &(inst->io_pwm_pin[j]), comp_id,
            "%s.io.pwm-pin.%01d", prefix, j);
        if(r != 0) return r;
    }
    r = hal_pin_bit_newf(HAL_IN, &(inst->motion_started), comp_id,
        "%s.motion.started", prefix);
    if(r != 0) return r;
    *(inst->motion_started) = false;
    for(j=0; j < (6); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->motion_override_limit[j]), comp_id,
            "%s.motion.override-limit.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (3); j++) {
        r = hal_pin_float_newf(HAL_OUT, &(inst->axis_position_feedback[j]), comp_id,
            "%s.axis.%01d.position-feedback", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (3); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->axis_limit_positive[j]), comp_id,
            "%s.axis.%01d.limit-positive", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (3); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->axis_limit_negative[j]), comp_id,
            "%s.axis.%01d.limit-negative", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (3); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->axis_home[j]), comp_id,
            "%s.axis.%01d.home", prefix, j);
        if(r != 0) return r;
    }
    r = hal_param_s32_newf(HAL_RW, &(inst->internal_state), comp_id,
        "%s.internal-state", prefix);
    inst->internal_state = -1;
    if(r != 0) return r;
    r = hal_param_u32_newf(HAL_RW, &(inst->device_serial), comp_id,
        "%s.device-serial", prefix);
    inst->device_serial = 0;
    if(r != 0) return r;
    r = hal_param_s32_newf(HAL_RW, &(inst->log_level), comp_id,
        "%s.log-level", prefix);
    inst->log_level = -1;
    if(r != 0) return r;
    for(j=0; j < (3); j++) {
        r = hal_param_float_newf(HAL_RW, &(inst->axis_step_scale[j]), comp_id,
            "%s.axis.%01d.step-scale", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (5); j++) {
        r = hal_param_s32_newf(HAL_RW, &(inst->io_input_pin_number[j]), comp_id,
            "%s.io.input-pin-number.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (5); j++) {
        r = hal_param_s32_newf(HAL_RW, &(inst->io_output_pin_number[j]), comp_id,
            "%s.io.output-pin-number.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (6); j++) {
        r = hal_param_s32_newf(HAL_RW, &(inst->io_pwm_pin_number[j]), comp_id,
            "%s.io.pwm-pin-number.%01d", prefix, j);
        if(r != 0) return r;
    }
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
char *names[16] = {0,};
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("PoKeysController");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "PoKeysController.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        int max_names = sizeof(names)/sizeof(names[0]);
        for(i=0; (i < max_names) && names[i]; i++) {
            if (strlen(names[i]) < 1) {
                rtapi_print_msg(RTAPI_MSG_ERR, "names[%d] is invalid (empty string)\n", i);
                r = -EINVAL;
                break;
            }
            r = export(names[i], i);
            if(r != 0) break;
       }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}
static void user_mainloop(void);

int __comp_parse_count(int *argc, char **argv) {
    int i;
    for (i = 0; i < *argc; i ++) {
        if (strncmp(argv[i], "count=", 6) == 0) {
            errno = 0;
            count = strtoul(&argv[i][6], NULL, 0);
            for (; i+1 < *argc; i ++) {
                argv[i] = argv[i+1];
            }
            argv[i] = NULL;
            (*argc)--;
            if (errno == 0) {
                return 1;
            }
        }
    }
    return 0;
}


int __comp_parse_names(int *argc, char **argv) {
    int i;
    for (i = 0; i < *argc; i ++) {
        if (strncmp(argv[i], "names=", 6) == 0) {
            char *p = &argv[i][6];
            int j;
            for (; i+1 < *argc; i ++) {
                argv[i] = argv[i+1];
            }
            argv[i] = NULL;
            (*argc)--;
            for (j = 0; j < 16; j ++) {
                names[j] = strtok(p, ",");
                p = NULL;
                if (names[j] == NULL) {
                    return 1;
                }
            }
            return 1;
        }
    }
    return 0;
}

int argc=0; char **argv=0;
int main(int argc_, char **argv_) {
    argc = argc_; argv = argv_;
    int found_count, found_names;
    found_count = __comp_parse_count(&argc, argv);
    found_names = __comp_parse_names(&argc, argv);
    if (found_count && found_names) {
        rtapi_print_msg(RTAPI_MSG_ERR, "count= and names= are mutually exclusive\n");
        return 1;
    }

    if(rtapi_app_main() < 0) return 1;
    user_mainloop();
    rtapi_app_exit();
    return 0;
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef machine_estop
#define machine_estop (*__comp_inst->machine_estop)
#undef machine_is_on
#define machine_is_on (0+*__comp_inst->machine_is_on)
#undef io_input_pin
#define io_input_pin(i) (*(__comp_inst->io_input_pin[i]))
#undef io_output_pin
#define io_output_pin(i) (0+*(__comp_inst->io_output_pin[i]))
#undef io_solid_state_relay
#define io_solid_state_relay(i) (0+*(__comp_inst->io_solid_state_relay[i]))
#undef io_relay
#define io_relay(i) (0+*(__comp_inst->io_relay[i]))
#undef io_open_collector
#define io_open_collector(i) (0+*(__comp_inst->io_open_collector[i]))
#undef io_pwm_pin
#define io_pwm_pin(i) (0+*(__comp_inst->io_pwm_pin[i]))
#undef motion_started
#define motion_started (0+*__comp_inst->motion_started)
#undef motion_override_limit
#define motion_override_limit(i) (0+*(__comp_inst->motion_override_limit[i]))
#undef axis_position_feedback
#define axis_position_feedback(i) (*(__comp_inst->axis_position_feedback[i]))
#undef axis_limit_positive
#define axis_limit_positive(i) (*(__comp_inst->axis_limit_positive[i]))
#undef axis_limit_negative
#define axis_limit_negative(i) (*(__comp_inst->axis_limit_negative[i]))
#undef axis_home
#define axis_home(i) (*(__comp_inst->axis_home[i]))
#undef internal_state
#define internal_state (__comp_inst->internal_state)
#undef device_serial
#define device_serial (__comp_inst->device_serial)
#undef log_level
#define log_level (__comp_inst->log_level)
#undef axis_step_scale
#define axis_step_scale(i) (__comp_inst->axis_step_scale[i])
#undef io_input_pin_number
#define io_input_pin_number(i) (__comp_inst->io_input_pin_number[i])
#undef io_output_pin_number
#define io_output_pin_number(i) (__comp_inst->io_output_pin_number[i])
#undef io_pwm_pin_number
#define io_pwm_pin_number(i) (__comp_inst->io_pwm_pin_number[i])
#undef FOR_ALL_INSTS
#define FOR_ALL_INSTS() struct __comp_state *__comp_inst; for(__comp_inst = __comp_first_inst; __comp_inst; __comp_inst = __comp_inst->_next)

// ------------------------------------
// Component code starts here
// ------------------------------------
#define ComponentStruct __comp_state    // Internal struct of linuxCNC component
#define InstanceVariable __comp_inst    // Internal variable of linuxCNC component

#define NumberOfAxis 3
#define NumberOfOverridePins 6    // Reasons for override might be more than one per Axis. Example shared homing/limit switches.
#define EstopPinNumber 51         // 0-based pin 52
#define NumberOfDigitalPins 5     // Applies to both input and output pins. Could be raised as necessary
#define CycleTimeMs 5.0f          // Target cycle time of uspace component
#define SharedMemoryKey 57        // Arbitrary number
#define EndOfMotionPacket 0x0101  // Arbitrary number > uint8

// ------------------------------------
// States of the component
// ------------------------------------
enum State {
    CREATED = -1,           // Component created, but not yet parametrized 
    INIT = 0,               // Start connection (Set externally only)
    IDLE = 1,               // Connected and PE stopped state
    ENABLED = 2,            // Connected and PE running state (not moving)
    MOVING = 3,             // Connected and PE running state (moving)
    ESTOP = 4,              // ESTOP toggled
    SHUTDOWN = 5,           // Exit component (Set externally only)
};

// ------------------------------------
// Function declarations
// ------------------------------------
bool ConnectPokeysDevice(struct ComponentStruct* componentInstance);
void ReadPulseEngineStatus(struct ComponentStruct* componentInstance);
void SetPulseEngineStatus(struct ComponentStruct* componentInstance, enum ePK_PEState state, const char* log);
void ProcessLimitOverride(struct ComponentStruct* componentInstance);
void ProcessEStop(struct ComponentStruct* componentInstance);
void ProcessDigitalPins(struct ComponentStruct* componentInstance);
void ProcessPwmPins(struct ComponentStruct* componentInstance);
void ProcessMoveCommand(struct ComponentStruct* componentInstance);
void ProcessPositions(struct ComponentStruct* componentInstance);
void ProcessRelays(struct ComponentStruct* componentInstance);
bool CompareRelayState(bool state, int offset);
void SetActiveOutputsOff(struct ComponentStruct* componentInstance);
struct timespec* GetStartTime();
void ProcessCycleTime(struct timespec* startTime, bool overrideCycleTime, enum State currentState, enum State nextState);
const char* GetStateName(enum State state);
void PrintElapsedTime(struct timespec* startTime, const char* log);

// ------------------------------------
// Main Loop
// ------------------------------------
void user_mainloop(void) {
    bool run = true;
    while(run) {
        FOR_ALL_INSTS() {
            bool overrideCycleTime = false;
            enum State originState = internal_state;
            struct timespec* cycleStart = GetStartTime();

            switch (internal_state) {
                case CREATED:
                    // Wait until prince HAL awakes us.
                    usleep(1000);
                    overrideCycleTime = true;
                    break;

                case INIT:
                    if (!ConnectPokeysDevice(InstanceVariable)) {
                        run = false; // TODO can we inform lcnc somehow that it will shutdown?
                        return;
                    }

                    internal_state = IDLE;
                    overrideCycleTime = true;
                    break;

                case IDLE:
                    ReadPulseEngineStatus(InstanceVariable);
                    ProcessEStop(InstanceVariable);

                    // Set Estop from PoKeys
                    if (machine_estop == true) {
                        internal_state = ESTOP;
                        break;
                    }

                    // Machine is enabled from LinuxCNC
                    if (machine_is_on == true) {
                        SetPulseEngineStatus(InstanceVariable, PK_PEState_peRUNNING, "Set PE Running from IDLE");
                        internal_state = ENABLED;
                        break;
                    }

                    ProcessDigitalPins(InstanceVariable);
                    ProcessPositions(InstanceVariable);
                    ProcessRelays(InstanceVariable);
                    ProcessPwmPins(InstanceVariable);
                    ProcessLimitOverride(InstanceVariable);

                    break;

                case ENABLED:
                    ReadPulseEngineStatus(InstanceVariable);
                    ProcessEStop(InstanceVariable);

                    // Set Estop from PoKeys
                    if (machine_estop == true) {
                        internal_state = ESTOP;
                        break;
                    }

                    // Machine is disabled from LinuxCNC
                    if (machine_is_on == false) {
                        SetPulseEngineStatus(InstanceVariable, PK_PEState_peSTOPPED, "Set PE Stopped from ENABLED");
                        internal_state = IDLE;
                        break;
                    }

                    ProcessDigitalPins(InstanceVariable);
                    ProcessPositions(InstanceVariable);
                    ProcessRelays(InstanceVariable);
                    ProcessPwmPins(InstanceVariable);
                    ProcessLimitOverride(InstanceVariable);

                    // Check if motion is commanded
                    if (motion_started == true) {
                        // switching states gives us at most "CycleTimeMs" of buffer.
                        // sleep specific time to give the buffer extra time (20ms) to fill up.
                        usleep(20000);
                        overrideCycleTime = true;
                        rtapi_print_msg(RTAPI_MSG_DBG, "Going to motion\n");
                        internal_state = MOVING;
                        break;
                    }

                    break;
                case MOVING:
                    ProcessMoveCommand(InstanceVariable);
                    ProcessEStop(InstanceVariable);

                    // Set Estop from PoKeys 
                    if (machine_estop == true) {
                        // TODO Can we somehow assert that the MotionBuffer does not add to the stream?
                        internal_state = ESTOP;
                        break;
                    }

                    // Machine is disabled from LinuxCNC 
                    if (machine_is_on == false) {
                        SetPulseEngineStatus(InstanceVariable, PK_PEState_peSTOPPED, "Set PE Stopped from MOVING(!)");
                        // TODO Can we somehow assert that the MotionBuffer does not add to the stream?
                        internal_state = IDLE;
                        break;
                    }

                    ProcessDigitalPins(InstanceVariable);
                    ProcessPositions(InstanceVariable);
                    ProcessRelays(InstanceVariable);
                    ProcessPwmPins(InstanceVariable);

                    break;
                case ESTOP:
                    ReadPulseEngineStatus(InstanceVariable);
                    ProcessDigitalPins(InstanceVariable); // necessary to update E-Stop pin
                    ProcessEStop(InstanceVariable);

                    // Reset Estop from PoKeys
                    if (machine_estop == false) {
                        internal_state = IDLE;
                        break;
                    }

                    break;
                case SHUTDOWN:
                    SetPulseEngineStatus(InstanceVariable, PK_PEState_peSTOPPED, "Set PE Stopped from SHUTDOWN");
                    SetActiveOutputsOff(InstanceVariable);

                    run = false;
                    return;
            }

            ProcessCycleTime(cycleStart, overrideCycleTime, originState, internal_state);
        }
    }
}

// ------------------------------------
// Undefine the component members, otherwise passing the comp_state and using it will break.
// Alternative: write a C component implementation
// ------------------------------------
#undef machine_estop
#undef machine_is_on
#undef io_input_pin
#undef io_input_pin_number
#undef io_output_pin
#undef io_output_pin_number
#undef io_solid_state_relay
#undef io_relay
#undef io_open_collector
#undef io_pwm_pin
#undef io_pwm_pin_number
#undef motion_started
#undef motion_override_limit
#undef axis_position_feedback
#undef axis_limit_positive
#undef axis_limit_negative
#undef axis_home
#undef internal_state
#undef device_serial
#undef log_level
#undef axis_step_scale

// ------------------------------------
// Connects to the device.
// Returns false if connection was unsuccessful, or the configuration is not matching.
// ------------------------------------
bool ConnectPokeysDevice(struct ComponentStruct* componentInstance) {
    if (componentInstance->log_level > -1) {
        rtapi_set_msg_level(componentInstance->log_level);
    }

    if (componentInstance->device_serial == 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "No 'device-serial' set!\n");
        return false;
    }

    sPoKeysDevice* device = PK_ConnectToDeviceWSerial(componentInstance->device_serial, 2000);
    if (device == 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "FAILED to Connect to device '%d'\n", componentInstance->device_serial);
        return false;
    }

    componentInstance->device = device;

    switch (device->DeviceData.DeviceType)
    {
        //case ePK_DeviceTypeID.PK_DeviceID_PoKeys57CNC:
        //case ePK_DeviceTypeID.PK_DeviceID_PoKeys57CNCpro4x25:
        case 32:
        case 33:
            rtapi_print_msg(RTAPI_MSG_INFO, "CONNECTED.\n");
            break;
        default:
            rtapi_print_msg(RTAPI_MSG_WARN, "CONNECTED. Unsupported device type: %d\n", device->DeviceData.DeviceType);
            break;
    }

    if (device->connectionType == 0) {
        // connection 0=USB, 1=ETH, 2=FastUSB
        rtapi_print_msg(RTAPI_MSG_WARN, "Connection type is standard USB mode. Enable FastUSB!\n", device->connectionType);
    }

    bool configurationOk = true;

    ReadPulseEngineStatus(componentInstance);

    if (device->PEv2.PulseEngineState != PK_PEState_peSTOPPED) {
        SetPulseEngineStatus(InstanceVariable, PK_PEState_peSTOPPED, "Set PE stopped on connect(!)");
    }

    int ret;
    // Check basic PE setup.
    // 0=Use external pulse generator and 1<<7=IO (PoKeysCNCaddon)
    if (device->PEv2.PulseEngineEnabled != NumberOfAxis || !(device->PEv2.PulseGeneratorType & (0 | (1<<7)))) {
        device->PEv2.PulseEngineEnabled = NumberOfAxis;
        device->PEv2.PulseGeneratorType = 0 | (1<<7);
        ret = PK_PEv2_PulseEngineSetup(device);
        rtapi_print_msg(RTAPI_MSG_WARN, "PE Setup:%d\n", ret);

        ret = PK_PEv2_PulseEngineReboot(device);
        rtapi_print_msg(RTAPI_MSG_DBG, "PE Reboot:%d\n", ret);
        // In theory we should sleep, but it'l highly unlikely you'll start a motion 1 second after opening LCNC.
        // TOOD or is the device communication down during this time?
    }

    // Set up axis configuration
    for (int i = 0; i < NumberOfAxis; i++) {
        device->PEv2.param1 = i;
        ret = PK_PEv2_AxisConfigurationGet(device);

        if (device->PEv2.AxesConfig[i] & (PK_AC_INTERNAL_PLANNER)) {
            device->PEv2.AxesConfig[i] &= ~(PK_AC_INTERNAL_PLANNER); // NOT internal => Buffer operated
            device->PEv2.param1 = i; // redundant?
            ret = PK_PEv2_AxisConfigurationSet(device);
            rtapi_print_msg(RTAPI_MSG_INFO, "PE axis %d configured:%d\n", i, ret);
        }
    }

    // Read and verify digital pin capabilities with HAL configuration
    ret = PK_PinConfigurationGet(device);
    rtapi_print_msg(RTAPI_MSG_DBG, "Getting pin info =%d\n", ret);

    for (int i = 0; i < NumberOfDigitalPins; i++) {
        int pinNumber = componentInstance->io_input_pin_number[i];

        if (pinNumber > 0) {
            uint8_t pinFunction = device->Pins[pinNumber - 1].PinFunction;

            if (pinFunction == 2) {
                rtapi_print_msg(RTAPI_MSG_INFO, "Pin mapping %d => %d digital read ok\n", i, pinNumber);
            } else {
                rtapi_print_msg(RTAPI_MSG_ERR, "Pin mapping %d => %d digital read nok, actual: %d\n", i, pinNumber, pinFunction);
                configurationOk = false;
            }
        }

        pinNumber = componentInstance->io_output_pin_number[i];

        if (pinNumber > 0) {
            uint8_t pinFunction = device->Pins[pinNumber - 1].PinFunction;

            if (pinFunction == 4) {
                rtapi_print_msg(RTAPI_MSG_INFO, "Pin mapping %d => %d digital write ok\n", i, pinNumber);
            } else {
                rtapi_print_msg(RTAPI_MSG_ERR, "Pin mapping %d => %d digital write nok, actual: %d\n", i, pinNumber, pinFunction);
                configurationOk = false;
            }
        }
    }

    // Read PWM pin capabilities
    ret = PK_PWMConfigurationGet(device);
    //rtapi_print_msg(RTAPI_MSG_DBG, "Getting PWM info =%d\n", ret);
    for (int i = 0; i < 6; i++)
    {
        int pinNumber = componentInstance->io_pwm_pin_number[i];

        if (pinNumber > 0) {
            if (device->PWM.PWMpinIDs[i] != pinNumber) {
                rtapi_print_msg(RTAPI_MSG_ERR, "PWM channel %d, mapped to pin %d, but is actually %d\n", i, pinNumber, device->PWM.PWMpinIDs[i]);
                configurationOk = false;
            }

            if (device->PWM.PWMenabledChannels[i] == false) {
                rtapi_print_msg(RTAPI_MSG_ERR, "PWM channel %d, mapped to pin %d, but is disabled\n", i, pinNumber);
                configurationOk = false;
            }
        }

        // TODO fill in a list of valid/enabled pwm pins and iterate over that?
    }

    return configurationOk;
}

// ------------------------------------
// Read the PulseEngines state, and positions and limits etc.
// Also reads extended device status: IO, analog, encoders
// ------------------------------------
void ReadPulseEngineStatus(struct ComponentStruct* componentInstance) {
    //struct timespec* requestStart = GetStartTime();
    int ret = PK_PEv2_StatusGet(componentInstance->device);
    //PrintElapsedTime(requestStart, "Getting PE STATE");
    rtapi_print_msg(RTAPI_MSG_DBG, "Getting status:%d, state=%d, limitOverride=%d\n", ret, componentInstance->device->PEv2.PulseEngineState, componentInstance->device->PEv2.LimitOverride);
}

// ------------------------------------
// Sets the PulseEngines state
// ------------------------------------
void SetPulseEngineStatus(struct ComponentStruct* componentInstance, enum ePK_PEState state, const char* log) {
    componentInstance->device->PEv2.PulseEngineStateSetup = state;

    //struct timespec* requestStart = GetStartTime();
    int ret = PK_PEv2_PulseEngineStateSet(componentInstance->device);
    //PrintElapsedTime(requestStart, "Setting PE STATE");

    rtapi_print_msg(RTAPI_MSG_INFO, "%s:%d\n", log, ret);
}

// ------------------------------------
// If any pin is enabled, the limit switches will be overridden, we forward that to the PE.
// Note: LCNC will reset the axis override as soon as the (jogging-)motion has finished.
// ------------------------------------
void ProcessLimitOverride(struct ComponentStruct* componentInstance) {
    bool limitOverride = false;
    sPoKeysDevice* device = componentInstance->device;

    for (int i = 0; i < NumberOfOverridePins; i++) {
        limitOverride |= *componentInstance->motion_override_limit[i];
    }

    if (limitOverride == true && device->PEv2.LimitOverride == 0) {
        device->PEv2.LimitOverrideSetup = 1;
        int ret = PK_PEv2_PulseEngineStateSet(device);
        rtapi_print_msg(RTAPI_MSG_WARN, "SET LIMIT OVERRIDE TRUE:%d\n", ret);
    } else if (limitOverride == false && device->PEv2.LimitOverride == 1) {
        device->PEv2.LimitOverrideSetup = 0;
        int ret = PK_PEv2_PulseEngineStateSet(device);
        rtapi_print_msg(RTAPI_MSG_WARN, "SET LIMIT OVERRIDE FALSE:%d\n", ret);
    }
}

// ------------------------------------
// Reads the PulseEngine status, if an emergency stop has occured.
// Since the PE will not reset when the switch is changed, we switch to stopped and from then on read the raw pin.
// ------------------------------------
void ProcessEStop(struct ComponentStruct* componentInstance) {
    if (componentInstance->device->PEv2.PulseEngineState == PK_PEState_peSTOP_EMERGENCY) {
        rtapi_print_msg(RTAPI_MSG_ERR, "E-Stop due to PulseEngine\n");

        *componentInstance->machine_estop = true;

        SetPulseEngineStatus(componentInstance, PK_PEState_peSTOPPED, "Set PE stopped due to ESTOP!");
        SetActiveOutputsOff(componentInstance);
    } else {
		bool currentEstop = 0 + *componentInstance->machine_estop;

        uint8_t eStopPin = componentInstance->device->Pins[EstopPinNumber].DigitalValueGet;
		rtapi_print_msg(RTAPI_MSG_DBG, "Getting E-Stop:%d\n", eStopPin);

		if (currentEstop == 1 && eStopPin == 0) {
			rtapi_print_msg(RTAPI_MSG_WARN, "E-Stop is Reset (by pin)\n");

			*componentInstance->machine_estop = false;

		} else if (currentEstop == 0 && eStopPin > 0) {
			rtapi_print_msg(RTAPI_MSG_ERR, "E-Stop due to pin!\n");

			*componentInstance->machine_estop = true;

            SetActiveOutputsOff(componentInstance);
		}
    }
}

// ------------------------------------
// Process output and input digital pins.
// ------------------------------------
void ProcessDigitalPins(struct ComponentStruct* componentInstance) {
    for (int i = 0; i < NumberOfDigitalPins; i++) {
        int pinNumber = componentInstance->io_output_pin_number[i];

        if (pinNumber > 0) {
            uint8_t pinState = *componentInstance->io_output_pin[i];
            componentInstance->device->Pins[pinNumber - 1].DigitalValueSet = pinState;
        }
    }

    //struct timespec* requestIoStart = GetStartTime();
    int ret = PK_DigitalIOSetGet(componentInstance->device);
    //PrintElapsedTime(requestIoStart, "Update all digital Pins");
    //rtapi_print_msg(RTAPI_MSG_DBG, "Update all digital pins:%d\n", ret); 

    for (int i = 0; i < NumberOfDigitalPins; i++) {
        int pinNumber = componentInstance->io_input_pin_number[i];

        if (pinNumber > 0) {
            uint8_t pinState = componentInstance->device->Pins[pinNumber - 1].DigitalValueGet;

            if (pinState > 0) {
                *componentInstance->io_input_pin[i] = true;
            } else {
                *componentInstance->io_input_pin[i] = false;
            }
        }
    }
}

// ------------------------------------
// Process PWM pins.
// ------------------------------------
void ProcessPwmPins(struct ComponentStruct* componentInstance) {
    bool setNecessary = false;
    sPoKeysDevice* device = componentInstance->device;

    for (int i = 0; i < 6; i++)
    {
        float pinValue = *componentInstance->io_pwm_pin[i];

        if (pinValue < 0.0f || pinValue > 100.0f) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PWM pin %d, exceeds range of 0.0 - 100.0!\n", i + 1);

            if (device->PWM.PWMduty[i] > 0.0f) {
                // something wrong, let's stop here.
                device->PWM.PWMduty[i] = 0;
                setNecessary = true;
            }
        } else if (pinValue == 0.0f && device->PWM.PWMduty[i] == 0) {
            continue;
        } else {
            uint32_t dutyCycle = ((pinValue / 100.0f) * (float)device->PWM.PWMperiod);

            if (device->PWM.PWMduty[i] - dutyCycle != 0) {
                rtapi_print_msg(RTAPI_MSG_DBG, "PWM Pin %d, set from %d to %d\n", i + 1, device->PWM.PWMduty[i], dutyCycle);
                device->PWM.PWMduty[i] = dutyCycle;
                setNecessary = true;
            }
        }
    }

    if (setNecessary) {
        int ret = PK_PWMUpdate(device);
        rtapi_print_msg(RTAPI_MSG_DBG, "Update PWM:%d\n", ret);
    }
}

// ------------------------------------
// Process streamed move command and implicitly update PE status information
// ------------------------------------
void ProcessMoveCommand(struct ComponentStruct* componentInstance) {
    hal_stream_t stream;
    int ret = hal_stream_attach(&stream, comp_id, SharedMemoryKey, "SSS");

    if (ret >= 0) {
        bool streamReadable = hal_stream_readable(&stream);

        if (!streamReadable) {
            // if the last cycle was slow (>5ms), we do not wait and almost "immediately" process the next motion state.
            // since the servo thread may not have updated yet, we delay here to get at least one value here.
            rtapi_print_msg(RTAPI_MSG_WARN, "Potential Buffer underrun? EndOfMotion Packet missing? Try sleep\n");
            usleep(500); // half the time of the servo period (1ms).
            streamReadable = hal_stream_readable(&stream);
        }

        if (streamReadable) {
            sPoKeysDevice* device = componentInstance->device;
            device->PEv2.motionBufferEntriesAccepted = 0;
            device->PEv2.newMotionBufferEntries = 0;

            int motionEntries = 0;

            //struct timespec* streamStart = GetStartTime();
            do
            {
                union hal_stream_data dataToReceive[NumberOfAxis];

                ret = hal_stream_read(&stream, dataToReceive, NULL);

                if (ret != 0) {
                    rtapi_print_msg(RTAPI_MSG_ERR, "Error reading stream:%d\n", ret);
                    continue;
                }

                if (dataToReceive[0].s == EndOfMotionPacket) {
                    rtapi_print_msg(RTAPI_MSG_DBG, "End of motion going to ENABLED state!\n");
                    componentInstance->internal_state = ENABLED;
                    break;
                }

                for (int i = 0; i < NumberOfAxis; i++) {
                    uint8_t motion = dataToReceive[i].s;
                    //rtapi_print_msg(RTAPI_MSG_ERR, "%d,", motion);
                    device->PEv2.MotionBuffer[(motionEntries * NumberOfAxis) + i] = motion;
                }

                //rtapi_print_msg(RTAPI_MSG_ERR, "\n");

                motionEntries++;

                streamReadable = hal_stream_readable(&stream);

                // floor(56 bytes / number of axes enabled) = floor(56 / 3) = 18 max allowable packet size
                if (streamReadable == false || motionEntries == 18) {
                    device->PEv2.newMotionBufferEntries = motionEntries;

                    //struct timespec* requestStart = GetStartTime();
                    ret = PK_PEv2_BufferFill(device);
                    //PrintElapsedTime(requestStart, "BufferFill");

                    if (device->PEv2.motionBufferEntriesAccepted != motionEntries) {
                        // TODO handle if not all buffer entries are accepted
                        rtapi_print_msg(RTAPI_MSG_ERR, "PE Axes NOT ALL BUFFER ENTRIES ACCEPTED (%d, accepted %d)%d\n", motionEntries, device->PEv2.motionBufferEntriesAccepted, ret);
                    }

                    motionEntries = 0;
                    //rtapi_print_msg(RTAPI_MSG_ERR, "PE Axes (%d, accepted %d), Move commanded:%d\n", motionEntries, device->PEv2.motionBufferEntriesAccepted, ret);
                }
            }
            while (streamReadable);

            //PrintElapsedTime(streamStart, "StreamRead");
        } else {
            rtapi_print_msg(RTAPI_MSG_ERR, "Buffer underrun? EndOfMotion Packet missing? Going to ENABLED state!\n");
            componentInstance->internal_state = ENABLED;
        }

        hal_stream_detach(&stream);
    } else {
        rtapi_print_msg(RTAPI_MSG_ERR, "Shared Buffer error=%d\n", ret);
    }
}

// ------------------------------------
// Updates the HAL pins based on the current PE position information.
// ------------------------------------
void ProcessPositions(struct ComponentStruct* componentInstance) {
    sPoKeysDevice* device = componentInstance->device;

    for (int i = 0; i < NumberOfAxis; i++) {
        *componentInstance->axis_position_feedback[i] = ((float)device->PEv2.CurrentPosition[i]) / ((float)componentInstance->axis_step_scale[i]);
        *componentInstance->axis_limit_positive[i] = (device->PEv2.LimitStatusP >> i) & 0x01;
        *componentInstance->axis_limit_negative[i] = (device->PEv2.LimitStatusN >> i) & 0x01;
        *componentInstance->axis_home[i] = (device->PEv2.HomeStatus >> i) & 0x01;

        //rtapi_print_msg(RTAPI_MSG_ERR, "Axis %d: %fmm, P%d, N%d, H%d", i, *componentInstance->axis_position_feedback[i], *componentInstance->axis_limit_positive[i], *componentInstance->axis_limit_negative[i], *componentInstance->axis_home[i]);
    }

    //rtapi_print_msg(RTAPI_MSG_ERR, "\n");
}

// ------------------------------------
// Process relays on/off
// ------------------------------------
void ProcessRelays(struct ComponentStruct* componentInstance) {
    sPoKeysDevice* device = componentInstance->device;

    //struct timespec* requestStart = GetStartTime();
    int ret = PK_PEv2_ExternalOutputsGet(device);
    //PrintElapsedTime(requestStart, "GetExternalOutputs");
    //rtapi_print_msg(RTAPI_MSG_DBG, "Getting Relay status:%d, %d\n", ret, device->PEv2.ExternalOCOutputs);

    bool ssr1on = 0 + *componentInstance->io_solid_state_relay[0];
    bool ssr2on = 0 + *componentInstance->io_solid_state_relay[1];
    bool relay1on = 0 + *componentInstance->io_relay[0];
    bool relay2on = 0 + *componentInstance->io_relay[1];
    bool oc1on = 0 + *componentInstance->io_open_collector[0];
    bool oc2on = 0 + *componentInstance->io_open_collector[1];
    bool oc3on = 0 + *componentInstance->io_open_collector[2];
    bool oc4on = 0 + *componentInstance->io_open_collector[3];

    bool setNecessary = false;
    setNecessary |= CompareRelayState(device, ssr1on, 7);
    setNecessary |= CompareRelayState(device, ssr2on, 0);
    setNecessary |= CompareRelayState(device, relay1on, 2);
    setNecessary |= CompareRelayState(device, relay2on, 1);
    setNecessary |= CompareRelayState(device, oc1on, 3);
    setNecessary |= CompareRelayState(device, oc2on, 4);
    setNecessary |= CompareRelayState(device, oc3on, 5);
    setNecessary |= CompareRelayState(device, oc4on, 6);

    if (setNecessary) {
        ret = PK_PEv2_ExternalOutputsSet(device);
        rtapi_print_msg(RTAPI_MSG_INFO, "Change relays:%d\n", ret);
    }
}

// ------------------------------------
// Compare actual relay state to expected state.
// On Pokeys57CNC the outputs are all accessed using ExternalOCOutputs! 0=SSR2, 7=SSR1, etc. See protocol definition.
// ------------------------------------
inline bool CompareRelayState(sPoKeysDevice* device, bool state, int offset) {
    if (state == true && ((device->PEv2.ExternalOCOutputs >> offset) & 0x01) == 0) {
        device->PEv2.ExternalOCOutputs |= (1 << offset);
        return true;
    } else if (state == false && ((device->PEv2.ExternalOCOutputs >> offset) & 0x01) == 1) {
        device->PEv2.ExternalOCOutputs &= (0 << offset);
        return true;
    }

    return false;
}

// ------------------------------------
// Set all relays and PWM outputs off.
// ------------------------------------
void SetActiveOutputsOff(struct ComponentStruct* componentInstance) {
    sPoKeysDevice* device = componentInstance->device;

    if (device->PEv2.ExternalOCOutputs > 0) {
        device->PEv2.ExternalOCOutputs = 0;
        int ret = PK_PEv2_ExternalOutputsSet(device);
        rtapi_print_msg(RTAPI_MSG_WARN, "Turn all relays off:%d\n", ret);
    }

    bool setNecessary = false;
    for (int i = 0; i < 6; i++)
    {
        if (device->PWM.PWMduty[i] > 0) {
            device->PWM.PWMduty[i] = 0;
            setNecessary = true;
        }
    }

    if (setNecessary) {
        int ret = PK_PWMUpdate(device);
        rtapi_print_msg(RTAPI_MSG_WARN, "Turn PWM off:%d\n", ret);
    }
}

// ------------------------------------
// Get the current timestamp. Consumer must free the memory of the timestamp!
// ------------------------------------
struct timespec* GetStartTime() {
    struct timespec* timeStamp;
    timeStamp = malloc(sizeof(struct timespec));
    clock_gettime(CLOCK_REALTIME, timeStamp);

    return timeStamp;
}

// ------------------------------------
// Try to keep the cycle time within defined limits.
// ------------------------------------
void ProcessCycleTime(struct timespec* cycleStart, bool overrideCycleTime, enum State currentState, enum State nextState) {
    struct timespec cycleEnd;
    clock_gettime(CLOCK_REALTIME, &cycleEnd);
    float t_ms = ((float)(cycleEnd.tv_sec - cycleStart->tv_sec) * 1.0e9 + (float)(cycleEnd.tv_nsec - cycleStart->tv_nsec)) / 1.0e6;
    free(cycleStart);

    rtapi_print_msg(RTAPI_MSG_DBG, "Time elapsed %f ms\n", t_ms);

    if (!overrideCycleTime) {
        if (t_ms <= CycleTimeMs) {
            useconds_t sleepTimeUs = (CycleTimeMs - t_ms) * 1000;
            usleep(sleepTimeUs);
        } else {
            const char* currentStateName = GetStateName(currentState);
            const char* nextStateName = GetStateName(nextState);

            if (t_ms <= CycleTimeMs + 3.0) {
                rtapi_print_msg(RTAPI_MSG_WARN, "Cycle greater than %fms elapsed %f ms, from %s to %s\n", CycleTimeMs, t_ms, currentStateName, nextStateName);
            } else {
                rtapi_print_msg(RTAPI_MSG_ERR, "Cycle greater than %f!ms elapsed %f ms, from %s to %s\n", CycleTimeMs, t_ms, currentStateName, nextStateName);
            }
        }
    }
}

// ------------------------------------
// Helper method to get the state enum name.
// ------------------------------------
inline const char* GetStateName(enum State state) {
    switch (state) {
        case CREATED: return "CREATED";
        case INIT: return "INIT";
        case IDLE: return "IDLE";
        case ENABLED: return "ENABLED";
        case MOVING: return "MOVING";
        case ESTOP: return "ESTOP";
        case SHUTDOWN: return "SHUTDOWN";
        default: return "UNDEFINED";
    }
}

// ------------------------------------
// Logs the difference of the timestamp and current time.
// ------------------------------------
void PrintElapsedTime(struct timespec* startTime, const char* log) {
    struct timespec endTime;
    clock_gettime(CLOCK_REALTIME, &endTime);
    float t_ms = ((float)(endTime.tv_sec - startTime->tv_sec) * 1.0e9 + (float)(endTime.tv_nsec - startTime->tv_nsec)) / 1.0e6;
    free(startTime);

    rtapi_print_msg(RTAPI_MSG_DBG, "%s took %f ms\n", log, t_ms);
}

static int __comp_get_data_size(void) { return 0; }
