/* Header mostly autogenerated by /usr/bin/halcompile, re-run --precompile PoKeysControllerPins.comp */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

// Component imports
#include "rtapi_math.h"		// For floor()
#include <PoKeysLib.h>      // For PoKeys communication
#include <time.h>           // For clock_gettime()
#include <unistd.h>         // For struct useconds_t
#include <inifile.h>	    // reading ini

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:PoKeysController:");
MODULE_INFO(linuxcnc, "pin:machine_estop:bit:0:out:Machine is in E-Stop condition:false:None");
MODULE_INFO(linuxcnc, "pin:machine_is_on:bit:0:in:Machine should be enabled:false:None");
MODULE_INFO(linuxcnc, "pin:io.input_pin.#:bit:10:out:Digital input pins:None:None");
MODULE_INFO(linuxcnc, "pin:io.output_pin.#:bit:10:in:Digital output pins:None:None");
MODULE_INFO(linuxcnc, "pin:io.solid_state_relay.#:bit:2:in:Solid state relays:None:None");
MODULE_INFO(linuxcnc, "pin:io.relay.#:bit:2:in:Relays:None:None");
MODULE_INFO(linuxcnc, "pin:io.open_collector.#:bit:4:in:Open collector digital outputs:None:None");
MODULE_INFO(linuxcnc, "pin:io.pwm_pin.#:float:6:in:PWM pins, valid values from 0.0 - 100.0 percent duty cycle:None:None");
MODULE_INFO(linuxcnc, "pin:io.encoder.#.count:s32:5:out:Encoders, raw count:None:None");
MODULE_INFO(linuxcnc, "pin:io.encoder.#.index:bit:5:out:Encoders, index triggered:None:None");
MODULE_INFO(linuxcnc, "pin:io.encoder.#.cps:float:5:out:Encoders, counts/second:None:None");
MODULE_INFO(linuxcnc, "pin:io.encoder.#.vps:float:5:out:Encoders, velocity [(count/scale)/second]:None:None");
MODULE_INFO(linuxcnc, "pin:motion.is_ready:bit:0:out:Indicates that the component is ready to accept motion commands:false:None");
MODULE_INFO(linuxcnc, "pin:motion.override_limit.#:bit:16:in:Limit switch override. Any pin set overrides globally on PoKeys:None:None");
MODULE_INFO(linuxcnc, "pin:axis.#.position_feedback:float:8:out:Position in machine units:None:None");
MODULE_INFO(linuxcnc, "pin:axis.#.limit_positive:bit:8:out:Positive limit switches:None:None");
MODULE_INFO(linuxcnc, "pin:axis.#.limit_negative:bit:8:out:Negative limit switches:None:None");
MODULE_INFO(linuxcnc, "pin:axis.#.home:bit:8:out:Home switches:None:None");
MODULE_INFO(linuxcnc, "param:internal_state:s32:0:rw:Current component state:0:None");
MODULE_INFO(linuxcnc, "param:axis.#.step_scale:float:8:rw:1 machine unit equals x pulses:None:None");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_INFO(linuxcnc, "author:T.Frei");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO

// Component extra configuration
#define ComponentStruct __comp_state    // Internal struct of component
#define NumberOfOverridePins 16         // Reasons for override might be more than one per Axis. Example shared homing/limit switches.
#define NumberOfDigitalPins 10          // Applies to both input and output pins. Could be raised as necessary
#define NumberOfEncoders 5              // Up to 25+1 encoders. Could be raised as necessary
#define NoEncoderIndex -127
#define EncoderBuffer 30                // 20 last values + 10 last averages
#define EncoderLastValues 20
#define UfEncoder 25                    // Ultra fast encoder 0-based index
#define EncoderLastAverages 10
#define EstopPinNumber 51               // 0-based pin 52
#define CycleTimeMs 5.0f                // Target cycle time of uspace component (200Hz)
#define SharedMemoryKey 57              // Arbitrary number
#define EndOfMotionPacket 0x0101        // Arbitrary number > uint8

typedef struct {
    uint32_t device_serial;
    uint8_t number_axes;
    uint8_t max_motion_packets;
    char streamtype[9];
    uint8_t input_pins;
    uint8_t input_pin_map[NumberOfDigitalPins];
    uint8_t output_pins;
    uint8_t output_pin_map[NumberOfDigitalPins];
    uint8_t pwm_pins;
    uint8_t pwm_pin_map[6]; // initially contains 1-based pin#, then 0-based channel#
    uint8_t encoders;
    uint8_t encoders_map[NumberOfEncoders];
    int8_t encoders_index_pin[NumberOfEncoders]; // contains both pin index and if the pin is inverted (negative number)
    float encoders_scale[NumberOfEncoders];
} component_configuration;

typedef struct {
    // elapsed cycles
    uint32_t cycles;
    // cycle when buffering started
    uint32_t cycleStartBuffer;
    // "Ring" buffer for velocity calculation
    uint8_t encoders_buffer_position[NumberOfEncoders][2];
    int32_t* encoders_buffer_values[NumberOfEncoders];
    // Comparative values for summing the encoder values
    int8_t encoders_value_previous[NumberOfEncoders];
} component_internals;

struct __comp_state {
    struct __comp_state* _next;
    hal_bit_t* machine_estop;
    hal_bit_t* machine_is_on;
    hal_bit_t* io_input_pin[NumberOfDigitalPins];
    hal_bit_t* io_output_pin[NumberOfDigitalPins];
    hal_bit_t* io_solid_state_relay[2];
    hal_bit_t* io_relay[2];
    hal_bit_t* io_open_collector[4];
    hal_float_t* io_pwm_pin[6];
    hal_s32_t* io_encoder_count[NumberOfEncoders];
    hal_bit_t* io_encoder_index[NumberOfEncoders];
    hal_float_t *io_encoder_cps[NumberOfEncoders];
    hal_float_t *io_encoder_vps[NumberOfEncoders];
    hal_bit_t *motion_is_ready;
    hal_bit_t* motion_override_limit[NumberOfOverridePins];
    hal_float_t* axis_position_feedback[8];
    hal_bit_t* axis_limit_positive[8];
    hal_bit_t* axis_limit_negative[8];
    hal_bit_t* axis_home[8];
    hal_s32_t internal_state;
    hal_float_t axis_step_scale[8];
    sPoKeysDevice* device;
    component_configuration* configuration;
    component_internals* internals;
};

#include <stdlib.h>
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

// Component configuration
static bool PMC_ReadConfiguration(const char *instanceName, struct ComponentStruct* componentInstance);

static int export(char *prefix, long extra_arg) {
    int r = 0;
    int j = 0;

    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);

    int configSize = sizeof(component_configuration);
    component_configuration* configuration = hal_malloc(configSize);
    memset(configuration, 0, sizeof(configSize));
    inst->configuration = configuration;

    int internalsSize = sizeof(component_internals);
    component_internals* internals = hal_malloc(internalsSize);
    memset(internals, 0, sizeof(internalsSize));
    inst->internals = internals;

    bool configOk = PMC_ReadConfiguration(prefix, inst);

    if (configOk == false) {
        return -321; // arbitrary number
    }

    r = hal_pin_bit_newf(HAL_OUT, &(inst->machine_estop), comp_id,
        "%s.machine-estop", prefix);
    if(r != 0) return r;
    *(inst->machine_estop) = false;
    r = hal_pin_bit_newf(HAL_IN, &(inst->machine_is_on), comp_id,
        "%s.machine-is-on", prefix);
    if(r != 0) return r;
    *(inst->machine_is_on) = false;
    for(j=0; j < (configuration->input_pins); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->io_input_pin[j]), comp_id,
            "%s.io.input-pin.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (configuration->output_pins); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->io_output_pin[j]), comp_id,
            "%s.io.output-pin.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (2); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->io_solid_state_relay[j]), comp_id,
            "%s.io.solid-state-relay.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (2); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->io_relay[j]), comp_id,
            "%s.io.relay.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (4); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->io_open_collector[j]), comp_id,
            "%s.io.open-collector.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (configuration->pwm_pins); j++) {
        r = hal_pin_float_newf(HAL_IN, &(inst->io_pwm_pin[j]), comp_id,
            "%s.io.pwm-pin.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (configuration->encoders); j++) {
        r = hal_pin_s32_newf(HAL_OUT, &(inst->io_encoder_count[j]), comp_id,
            "%s.io.encoder.%01d.count", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (configuration->encoders); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->io_encoder_index[j]), comp_id,
            "%s.io.encoder.%01d.index", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (configuration->encoders); j++) {
        r = hal_pin_float_newf(HAL_OUT, &(inst->io_encoder_cps[j]), comp_id,
            "%s.io.encoder.%01d.cps", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (configuration->encoders); j++) {
        r = hal_pin_float_newf(HAL_OUT, &(inst->io_encoder_vps[j]), comp_id,
            "%s.io.encoder.%01d.vps", prefix, j);
        if(r != 0) return r;
    }
    r = hal_pin_bit_newf(HAL_OUT, &(inst->motion_is_ready), comp_id,
        "%s.motion.is-ready", prefix);
    if(r != 0) return r;
    *(inst->motion_is_ready) = false;
    for(j=0; j < (NumberOfOverridePins); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->motion_override_limit[j]), comp_id,
            "%s.motion.override-limit.%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (configuration->number_axes); j++) {
        r = hal_pin_float_newf(HAL_OUT, &(inst->axis_position_feedback[j]), comp_id,
            "%s.axis.%01d.position-feedback", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (configuration->number_axes); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->axis_limit_positive[j]), comp_id,
            "%s.axis.%01d.limit-positive", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (configuration->number_axes); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->axis_limit_negative[j]), comp_id,
            "%s.axis.%01d.limit-negative", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (configuration->number_axes); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->axis_home[j]), comp_id,
            "%s.axis.%01d.home", prefix, j);
        if(r != 0) return r;
    }
    r = hal_param_s32_newf(HAL_RW, &(inst->internal_state), comp_id,
        "%s.internal-state", prefix);
    inst->internal_state = 0;
    if(r != 0) return r;
    for(j=0; j < (configuration->number_axes); j++) {
        r = hal_param_float_newf(HAL_RW, &(inst->axis_step_scale[j]), comp_id,
            "%s.axis.%01d.step-scale", prefix, j);
        if(r != 0) return r;
    }
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
char *names[16] = {0,};
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("PoKeysController");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "PoKeysController.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        int max_names = sizeof(names)/sizeof(names[0]);
        for(i=0; (i < max_names) && names[i]; i++) {
            if (strlen(names[i]) < 1) {
                rtapi_print_msg(RTAPI_MSG_ERR, "names[%d] is invalid (empty string)\n", i);
                r = -EINVAL;
                break;
            }
            r = export(names[i], i);
            if(r != 0) break;
       }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}
static void user_mainloop(void);

int __comp_parse_count(int *argc, char **argv) {
    int i;
    for (i = 0; i < *argc; i ++) {
        if (strncmp(argv[i], "count=", 6) == 0) {
            errno = 0;
            count = strtoul(&argv[i][6], NULL, 0);
            for (; i+1 < *argc; i ++) {
                argv[i] = argv[i+1];
            }
            argv[i] = NULL;
            (*argc)--;
            if (errno == 0) {
                return 1;
            }
        }
    }
    return 0;
}


int __comp_parse_names(int *argc, char **argv) {
    int i;
    for (i = 0; i < *argc; i ++) {
        if (strncmp(argv[i], "names=", 6) == 0) {
            char *p = &argv[i][6];
            int j;
            for (; i+1 < *argc; i ++) {
                argv[i] = argv[i+1];
            }
            argv[i] = NULL;
            (*argc)--;
            for (j = 0; j < 16; j ++) {
                names[j] = strtok(p, ",");
                p = NULL;
                if (names[j] == NULL) {
                    return 1;
                }
            }
            return 1;
        }
    }
    return 0;
}

int argc=0; char **argv=0;
int main(int argc_, char **argv_) {
    argc = argc_; argv = argv_;
    int found_count, found_names;
    found_count = __comp_parse_count(&argc, argv);
    found_names = __comp_parse_names(&argc, argv);
    if (found_count && found_names) {
        rtapi_print_msg(RTAPI_MSG_ERR, "count= and names= are mutually exclusive\n");
        return 1;
    }

    if(rtapi_app_main() < 0) return 1;
    user_mainloop();
    rtapi_app_exit();
    return 0;
}

static int __comp_get_data_size(void) { return 0; }

// ------------------------------------
// Component code starts here
// ------------------------------------

// ------------------------------------
// States of the component
// ------------------------------------
enum State {
    SHUTDOWN = -1,          // Exit component (Set externally only)
    INIT = 0,               // Component created
    IDLE = 1,               // Connected and PE stopped state
    ENABLED = 2,            // Connected and PE running state (not moving)
    MOTIONBUFFERING = 3,    // Connected and PE running state (buffer started streaming)
    MOVING = 4,             // Connected and PE running state (moving)
    MOTIONERROR = 5,        // Stop motion due to error
    MOTIONDISABLE = 6,      // Stop motion due to disabled machine
    MOTIONESTOP = 7,        // Stop motion due to emergency stop
    ESTOP = 8,              // Emergency stop toggled
};

// ------------------------------------
// Function declarations
// ------------------------------------
bool PMC_ConnectPokeysDevice(struct ComponentStruct* componentInstance);
void PMC_ReadPulseEngineStatus(struct ComponentStruct* componentInstance);
void PMC_SetPulseEngineStatus(struct ComponentStruct* componentInstance, enum ePK_PEState state, const char* log);
void PMC_ProcessLimitOverride(struct ComponentStruct* componentInstance);
void PMC_ProcessEStop(struct ComponentStruct* componentInstance);
void PMC_ProcessDigitalPins(struct ComponentStruct* componentInstance);
void PMC_ProcessPwmPins(struct ComponentStruct* componentInstance);
void PMC_ProcessEncoders(struct ComponentStruct* componentInstance);
bool PMC_StreamAvailable(struct ComponentStruct* componentInstance);
bool PMC_FinishStream(struct ComponentStruct* componentInstance);
enum State PMC_ProcessMoveCommand(struct ComponentStruct* componentInstance);
void PMC_ProcessPositions(struct ComponentStruct* componentInstance);
void PMC_ProcessRelays(struct ComponentStruct* componentInstance);
bool PMC_CompareRelayState(sPoKeysDevice* device, bool state, int offset);
void PMC_SetActiveOutputsOff(struct ComponentStruct* componentInstance);
struct timespec* PMC_GetStartTime();
void PMC_ProcessCycleTime(struct timespec* startTime, bool overrideCycleTime, enum State currentState, struct ComponentStruct* componentInstance);
const char* PMC_GetStateName(enum State state);

int32_t PMC_DigitalIOSetGet(struct ComponentStruct* componentInstance);

// ------------------------------------
// Main Loop
// ------------------------------------
void user_mainloop(void) {
    bool run = true;
    while(run) {
        struct ComponentStruct* currentInstance;
        for(currentInstance = __comp_first_inst; currentInstance; currentInstance = currentInstance->_next) {
            bool overrideCycleTime = false;
            struct timespec* cycleStart = PMC_GetStartTime();

            enum State originState = currentInstance->internal_state;
            switch (originState) {
                case INIT:
                    if (!PMC_ConnectPokeysDevice(currentInstance)) {
                        run = false; // TODO can we inform lcnc somehow that it will shutdown?
                        return;
                    }

                    currentInstance->internal_state = IDLE;
                    overrideCycleTime = true;
                    break;

                case IDLE:
                    PMC_ReadPulseEngineStatus(currentInstance);
                    PMC_ProcessEStop(currentInstance);

                    // Set Estop from PoKeys
                    if (*currentInstance->machine_estop == true) {
                        currentInstance->internal_state = ESTOP;
                        break;
                    }

                    // Machine is enabled from LinuxCNC
                    if (0 + *currentInstance->machine_is_on == true) {
                        PMC_SetPulseEngineStatus(currentInstance, PK_PEState_peRUNNING, "Set PE Running from IDLE");
                        *currentInstance->motion_is_ready = true;
                        currentInstance->internal_state = ENABLED;
                        break;
                    }

                    PMC_ProcessDigitalPins(currentInstance);
                    PMC_ProcessPositions(currentInstance);
                    PMC_ProcessRelays(currentInstance);
                    PMC_ProcessPwmPins(currentInstance);
                    PMC_ProcessEncoders(currentInstance);
                    PMC_ProcessLimitOverride(currentInstance);

                    break;

                case ENABLED:
                    PMC_ReadPulseEngineStatus(currentInstance);
                    PMC_ProcessEStop(currentInstance);

                    // Set Estop from PoKeys
                    if (*currentInstance->machine_estop == true) {
                        *currentInstance->motion_is_ready = false;
                        currentInstance->internal_state = ESTOP;
                        break;
                    }

                    // Machine is disabled from LinuxCNC
                    if (0 + *currentInstance->machine_is_on == false) {
                        PMC_SetPulseEngineStatus(currentInstance, PK_PEState_peSTOPPED, "Set PE Stopped from ENABLED");
                        *currentInstance->motion_is_ready = false;
                        currentInstance->internal_state = IDLE;
                        break;
                    }

                    PMC_ProcessDigitalPins(currentInstance);
                    PMC_ProcessPositions(currentInstance);
                    PMC_ProcessRelays(currentInstance);
                    PMC_ProcessPwmPins(currentInstance);
                    PMC_ProcessEncoders(currentInstance);
                    PMC_ProcessLimitOverride(currentInstance);

                    // Check if motion is commanded
                    if (PMC_StreamAvailable(currentInstance)) {
                        // switching states gives us at most "CycleTimeMs" of buffer.
                        // "Buffering" state will provide extra time (20ms) to fill up.
                        currentInstance->internals->cycleStartBuffer = currentInstance->internals->cycles;
                        currentInstance->internal_state = MOTIONBUFFERING;
                        break;
                    }

                    break;
                case MOTIONBUFFERING:
                    if (currentInstance->internals->cycles - currentInstance->internals->cycleStartBuffer >= 4) {
                        currentInstance->internal_state = MOVING;
                        break;
                    }

                    PMC_ReadPulseEngineStatus(currentInstance);
                    PMC_ProcessEStop(currentInstance);

                    // Set Estop from PoKeys
                    if (*currentInstance->machine_estop == true) {
                        *currentInstance->motion_is_ready = false;
                        currentInstance->internal_state = MOTIONESTOP;
                        break;
                    }

                    // Machine is disabled from LinuxCNC
                    if (0 + *currentInstance->machine_is_on == false) {
                        PMC_SetPulseEngineStatus(currentInstance, PK_PEState_peSTOPPED, "Set PE Stopped from ENABLED");
                        *currentInstance->motion_is_ready = false;
                        currentInstance->internal_state = MOTIONDISABLE;
                        break;
                    }

                    PMC_ProcessDigitalPins(currentInstance);
                    PMC_ProcessPositions(currentInstance);
                    PMC_ProcessRelays(currentInstance);
                    PMC_ProcessPwmPins(currentInstance);
                    PMC_ProcessEncoders(currentInstance);
                    PMC_ProcessLimitOverride(currentInstance);

                    break;
                case MOVING:
                    currentInstance->internal_state = PMC_ProcessMoveCommand(currentInstance);

                    PMC_ProcessEStop(currentInstance);

                    // Set Estop from PoKeys
                    if (*currentInstance->machine_estop == true) {
                        *currentInstance->motion_is_ready = false;
                        currentInstance->internal_state = MOTIONESTOP;
                        break;
                    }

                    // Machine is disabled from LinuxCNC
                    if (0 + *currentInstance->machine_is_on == false) {
                        PMC_SetPulseEngineStatus(currentInstance, PK_PEState_peSTOPPED, "Set PE Stopped from MOVING(!)");
                        *currentInstance->motion_is_ready = false;
                        currentInstance->internal_state = MOTIONDISABLE;
                        break;
                    }

                    PMC_ProcessDigitalPins(currentInstance);
                    PMC_ProcessPositions(currentInstance);
                    PMC_ProcessRelays(currentInstance);
                    PMC_ProcessPwmPins(currentInstance);
                    PMC_ProcessEncoders(currentInstance);

                    break;
                case MOTIONERROR:
                    // Most likely error, buffer underrun. Return to enabled state and retry.
                    currentInstance->internal_state = ENABLED;
                    break;
                case MOTIONDISABLE:
                    if (PMC_FinishStream(currentInstance)) {
                        overrideCycleTime = true;
                        currentInstance->internal_state = IDLE;
                        break;
                    }

                    PMC_ProcessDigitalPins(currentInstance);
                    PMC_ProcessPositions(currentInstance);
                    PMC_ProcessRelays(currentInstance);
                    PMC_ProcessPwmPins(currentInstance);
                    PMC_ProcessEncoders(currentInstance);

                    break;
                case MOTIONESTOP:
                    if (PMC_FinishStream(currentInstance)) {
                        overrideCycleTime = true;
                        currentInstance->internal_state = ESTOP;
                        break;
                    }

                    PMC_ProcessDigitalPins(currentInstance);
                    PMC_ProcessPositions(currentInstance);
                    PMC_ProcessRelays(currentInstance);
                    PMC_ProcessPwmPins(currentInstance);
                    PMC_ProcessEncoders(currentInstance);

                    break;
                case ESTOP:
                    PMC_ReadPulseEngineStatus(currentInstance);
                    PMC_ProcessDigitalPins(currentInstance); // necessary to update E-Stop pin
                    PMC_ProcessEStop(currentInstance);

                    // Reset Estop from PoKeys
                    if (*currentInstance->machine_estop == false) {
                        currentInstance->internal_state = IDLE;
                        break;
                    }

                    break;
                case SHUTDOWN:
                    if (currentInstance->device != NULL) {
                        PMC_SetPulseEngineStatus(currentInstance, PK_PEState_peSTOPPED, "Set PE Stopped from SHUTDOWN");
                        PMC_SetActiveOutputsOff(currentInstance);
                    }

                    run = false;
                    return;
            }

            PMC_ProcessCycleTime(cycleStart, overrideCycleTime, originState, currentInstance);
        }
    }
}

// ------------------------------------
// Reads the configuration from the INI file.
// ------------------------------------
bool PMC_ReadConfiguration(const char *instanceName, struct ComponentStruct* componentInstance) {
    const char* ini_path = getenv("INI_FILE_NAME");
    FILE* ini_file_ptr = fopen(ini_path, "r");

    if (ini_file_ptr == NULL) {
        rtapi_print_msg(RTAPI_MSG_ERR, "FAILED to read INI '%s'\n", ini_path);
        return false;
    }

    const char* levelTag = "LOG_LEVEL";
    int logLevel = 0;
    int iniRead = iniFindInt(ini_file_ptr, levelTag, instanceName, &logLevel);

    if (iniRead == 0 && logLevel > -1) {
        rtapi_set_msg_level(logLevel);
    }

    component_configuration* configuration = componentInstance->configuration;

    // Read device serial
    const char* serialTag = "DEVICE_SERIAL";
    int deviceSerial = 0;
    iniRead = iniFindInt(ini_file_ptr, serialTag, instanceName, &deviceSerial);

    if (iniRead != 0 || deviceSerial == 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "No device serial in INI set! '%d'\n", iniRead);
        fclose(ini_file_ptr);
        return false;
    }

    configuration->device_serial = deviceSerial;

    // Read and apply axes relevant configuration
    const char* axisTag = "NUMBER_AXES";
    int numberOfAxes = 0;
    iniRead = iniFindInt(ini_file_ptr, axisTag, instanceName, &numberOfAxes);

    if (iniRead != 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "Number of axes not set in INI! '%d'\n", iniRead);
        fclose(ini_file_ptr);
        return false;
    }

    if (numberOfAxes < 1 || numberOfAxes > 8) {
        rtapi_print_msg(RTAPI_MSG_ERR, "Number of axes invalid (1..8) '%d'\n", numberOfAxes);
        fclose(ini_file_ptr);
        return false;
    }

    configuration->number_axes = numberOfAxes;
    configuration->max_motion_packets = floor(56 / numberOfAxes);  // floor(56 bytes / number of axes enabled) = max allowable packet size

    for (int i=0; i < numberOfAxes; i++) {
        configuration->streamtype[i] = 'S';
    }
    configuration->streamtype[numberOfAxes] = 0; // null terminate manually

    // Read and apply input pin configuration
    uint8_t inputPins = 0;
    for (int i = 0; i < NumberOfDigitalPins; i++) {
        char inputPinTagFormat[14];
        rtapi_snprintf(inputPinTagFormat, 14, "INPUT_PIN_%d", i);

        int inputPin = 0;
        iniRead = iniFindInt(ini_file_ptr, inputPinTagFormat, instanceName, &inputPin);

        if (iniRead == 0) {
            configuration->input_pin_map[inputPins] = inputPin - 1;
            rtapi_print_msg(RTAPI_MSG_DBG, "Read input pin '%d' on HAL pin '%d'\n", inputPin, i);
            inputPins++;
        } else {
            break;
        }
    }
    configuration->input_pins = inputPins;

    // Read and apply output pin configuration
    uint8_t outputPins = 0;
    for (int i = 0; i < NumberOfDigitalPins; i++) {
        char outputPinTagFormat[15];
        rtapi_snprintf(outputPinTagFormat, 15, "OUTPUT_PIN_%d", i);

        int outputPin = 0;
        iniRead = iniFindInt(ini_file_ptr, outputPinTagFormat, instanceName, &outputPin);

        if (iniRead == 0) {
            configuration->output_pin_map[outputPins] = outputPin - 1;
            rtapi_print_msg(RTAPI_MSG_DBG, "Write output pin '%d' on HAL pin '%d'\n", outputPin, i);
            outputPins++;
        } else {
            break;
        }
    }
    configuration->output_pins = outputPins;

    // Read and apply PWM pin configuration
    uint8_t pwmPins = 0;
    for (int i = 0; i < 6; i++)
    {
        char pwmPinTagFormat[11];
        rtapi_snprintf(pwmPinTagFormat, 11, "PWM_PIN_%d", i);

        int pwmPin = 0;
        iniRead = iniFindInt(ini_file_ptr, pwmPinTagFormat, instanceName, &pwmPin);

        if (iniRead == 0) {
            configuration->pwm_pin_map[pwmPins] = pwmPin;
            rtapi_print_msg(RTAPI_MSG_DBG, "PWM pin '%d' on HAL pin '%d'\n", pwmPin, i);
            pwmPins++;
        } else {
            break;
        }
    }
    configuration->pwm_pins = pwmPins;

    // Read and apply encoder configuration
    uint8_t encoders = 0;
    for (int i = 0; i < NumberOfEncoders; i++)
    {
        char encoderTagFormat[32];
        rtapi_snprintf(encoderTagFormat, 32, "ENCODER_PIN_%d", i);

        int encoder = 0;
        iniRead = iniFindInt(ini_file_ptr, encoderTagFormat, instanceName, &encoder);

        if (iniRead == 0) {
            configuration->encoders_map[encoders] = encoder - 1;
            rtapi_print_msg(RTAPI_MSG_DBG, "Encoder '%d' on HAL pin '%d'\n", encoder, i);

            rtapi_snprintf(encoderTagFormat, 32, "ENCODER_PIN_%d_INDEX_PIN", i);
            int indexPin = 0;
            iniRead = iniFindInt(ini_file_ptr, encoderTagFormat, instanceName, &indexPin);

            if (iniRead == 0) {
                configuration->encoders_index_pin[encoders] = indexPin - 1;

                rtapi_snprintf(encoderTagFormat, 32, "ENCODER_PIN_%d_INDEX_PIN_INVERT", i);
                const char* invert = iniFind(ini_file_ptr, encoderTagFormat, instanceName);

                if (strcasecmp("true", invert) == 0) {
                    configuration->encoders_index_pin[encoders] = configuration->encoders_index_pin[encoders] * -1;
                }
            } else {
                configuration->encoders_index_pin[encoders] = NoEncoderIndex;
            }

            rtapi_snprintf(encoderTagFormat, 32, "ENCODER_PIN_%d_SCALE", i);
            double scale = 0;
            iniRead = iniFindDouble(ini_file_ptr, encoderTagFormat, instanceName, &scale);

            if (iniRead == 0) {
                configuration->encoders_scale[encoders] = scale;
            } else {
                configuration->encoders_scale[encoders] = 1;
            }

            // Allocate buffer only if encoders are actually used.
            int8_t bufferSize = sizeof(int32_t[EncoderBuffer]);
            componentInstance->internals->encoders_buffer_values[encoders] = hal_malloc(bufferSize);
            memset(componentInstance->internals->encoders_buffer_values[encoders], 0, bufferSize);

            encoders++;
        } else {
            break;
        }
    }
    configuration->encoders = encoders;

    fclose(ini_file_ptr);

    return true;
}

// ------------------------------------
// Connects to the device.
// Returns false if connection was unsuccessful, or the configuration is not matching.
// ------------------------------------
bool PMC_ConnectPokeysDevice(struct ComponentStruct* componentInstance) {
    component_configuration* configuration = componentInstance->configuration;

    sPoKeysDevice* device = PK_ConnectToDeviceWSerial(configuration->device_serial, 2000);
    if (device == 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "FAILED to Connect to device '%d'\n", configuration->device_serial);
        return false;
    }

    componentInstance->device = device;

    rtapi_print_msg(RTAPI_MSG_INFO, "CONNECTED.\n");

    if (device->connectionType == 0) {
        // connection 0=USB, 1=ETH, 2=FastUSB
        rtapi_print_msg(RTAPI_MSG_WARN, "Connection type is standard USB mode. Enable FastUSB!\n", device->connectionType);
    }

    bool configurationOk = true;

    PMC_ReadPulseEngineStatus(componentInstance);

    if (device->PEv2.PulseEngineState != PK_PEState_peSTOPPED) {
        PMC_SetPulseEngineStatus(componentInstance, PK_PEState_peSTOPPED, "Set PE stopped on connect(!)");
    }

    int ret;
    // Check if all axes are enabled.
    uint8_t numberOfAxes = configuration->number_axes;
    if (device->PEv2.PulseEngineEnabled != numberOfAxes) {
        device->PEv2.PulseEngineEnabled = numberOfAxes;
        ret = PK_PEv2_PulseEngineSetup(device);
        rtapi_print_msg(RTAPI_MSG_WARN, "PE axes setup:%d\n", ret);

        ret = PK_PEv2_PulseEngineReboot(device);
        rtapi_print_msg(RTAPI_MSG_DBG, "PE Reboot:%d\n", ret);
        // In theory we should sleep, but it'l highly unlikely you'll start a motion 1 second after opening LCNC.
    }

    // Set up axis configuration
    for (int i = 0; i < numberOfAxes; i++) {
        device->PEv2.param1 = i;
        ret = PK_PEv2_AxisConfigurationGet(device);

        if (device->PEv2.AxesConfig[i] & (PK_AC_INTERNAL_PLANNER)) {
            device->PEv2.AxesConfig[i] &= ~(PK_AC_INTERNAL_PLANNER); // NOT internal => Buffer operated
            device->PEv2.param1 = i; // redundant?
            ret = PK_PEv2_AxisConfigurationSet(device);
            rtapi_print_msg(RTAPI_MSG_INFO, "PE axis %d configured:%d\n", i, ret);
        }
    }

    // Read and verify digital pin capabilities with INI configuration
    ret = PK_PinConfigurationGet(device);
    rtapi_print_msg(RTAPI_MSG_DBG, "Getting pin info:%d\n", ret);

    for (int i = 0; i < configuration->input_pins; i++) {
        int pinNumber = configuration->input_pin_map[i];

        uint8_t pinFunction = device->Pins[pinNumber].PinFunction;

        if (pinFunction == 2) {
            rtapi_print_msg(RTAPI_MSG_INFO, "IO input pin %d => PoKeys pin %d, digital read ok\n", i, pinNumber + 1);
        } else {
            rtapi_print_msg(RTAPI_MSG_ERR, "IO input pin %d => PoKeys pin %d, digital read nok, actual function: %d\n", i, pinNumber + 1, pinFunction);
            configurationOk = false;
        }
    }

    for (int i = 0; i < configuration->output_pins; i++) {
        int pinNumber = configuration->output_pin_map[i];

        uint8_t pinFunction = device->Pins[pinNumber].PinFunction;

        if (pinFunction == 4) {
            rtapi_print_msg(RTAPI_MSG_INFO, "IO output pin %d => PoKeys pin %d, digital write ok\n", i, pinNumber + 1);
        } else {
            rtapi_print_msg(RTAPI_MSG_ERR, "IO output pin %d => PoKeys pin %d, digital write nok, actual function: %d\n", i, pinNumber + 1, pinFunction);
            configurationOk = false;
        }
    }

    // Read PWM pin capabilities
    ret = PK_PWMConfigurationGet(device);
    rtapi_print_msg(RTAPI_MSG_DBG, "Getting PWM info:%d\n", ret);

    for (int i = 0; i < configuration->pwm_pins; i++)
    {
        int pinNumber = configuration->pwm_pin_map[i];
        int channelNumber = -1;

        for (int i = 0; i < 6; i++) {
            if (device->PWM.PWMpinIDs[i] == pinNumber) {
                channelNumber = i;
                break;
            }
        }

        if (channelNumber == -1) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PWM pin %d, not matching any channel\n", pinNumber);
            configurationOk = false;
        } else if (device->PWM.PWMenabledChannels[channelNumber] == false) {
            rtapi_print_msg(RTAPI_MSG_ERR, "IO PWM pin %d => PoKeys pin %d, channel %d, but is disabled\n", i, pinNumber, channelNumber);
            configurationOk = false;
        } else {
            configuration->pwm_pin_map[i] = channelNumber;
            rtapi_print_msg(RTAPI_MSG_INFO, "IO PWM pin %d => PoKeys pin %d, channel %d, PWM ok\n", i, pinNumber, channelNumber);
        }
    }

    // Read Encoder configuration
    ret = PK_EncoderConfigurationGet(device);
    rtapi_print_msg(RTAPI_MSG_DBG, "Getting encoder info:%d\n", ret);

    // According to documentation "1" and "10" are the only active pin configurations
    if ((device->FastEncodersConfiguration & 1) == 1 || (device->FastEncodersConfiguration & 10) == 10) {
        rtapi_print_msg(RTAPI_MSG_DBG, "Fast encoders are enabled\n");
        // Fast encoder options are tracked separated, overwrite the basic encoder for simplicity
        device->Encoders[0].encoderOptions = 1;
        device->Encoders[1].encoderOptions = 1;
        device->Encoders[2].encoderOptions = 1;
    }

    if ((device->UltraFastEncoderConfiguration & 1) == 1) {
        rtapi_print_msg(RTAPI_MSG_DBG, "Ultra fast encoder is enabled\n");
        device->Encoders[UfEncoder].encoderOptions = 1;
    }

    for (int i = 0; i < configuration->encoders; i++) {
        int encoder = configuration->encoders_map[i];

        if (device->Encoders[encoder].encoderOptions & 0x01 == true) {
            rtapi_print_msg(RTAPI_MSG_INFO, "Encoder pin %d => PoKeys encoder %d, ok\n", i, encoder + 1);
        } else {
            rtapi_print_msg(RTAPI_MSG_ERR, "Encoder pin %d => PoKeys encoder %d, not enabled\n", i, encoder + 1);
            configurationOk = false;
        }
    }

    return configurationOk;
}

// ------------------------------------
// Read the PulseEngines state, and positions and limits etc.
// Also reads extended device status: IO, analog, encoders
// ------------------------------------
void PMC_ReadPulseEngineStatus(struct ComponentStruct* componentInstance) {
    int ret = PK_PEv2_StatusGet(componentInstance->device);
    rtapi_print_msg(RTAPI_MSG_DBG, "Getting status:%d, state=%d, limitOverride=%d\n", ret, componentInstance->device->PEv2.PulseEngineState, componentInstance->device->PEv2.LimitOverride);
}

// ------------------------------------
// Sets the PulseEngines state
// ------------------------------------
void PMC_SetPulseEngineStatus(struct ComponentStruct* componentInstance, enum ePK_PEState state, const char* log) {
    componentInstance->device->PEv2.PulseEngineStateSetup = state;
    int ret = PK_PEv2_PulseEngineStateSet(componentInstance->device);
    rtapi_print_msg(RTAPI_MSG_INFO, "%s:%d\n", log, ret);
}

// ------------------------------------
// If any pin is enabled, the limit switches will be overridden, we forward that to the PE.
// Note: LCNC will reset the axis override as soon as the (jogging-)motion has finished.
// ------------------------------------
void PMC_ProcessLimitOverride(struct ComponentStruct* componentInstance) {
    bool limitOverride = false;
    sPoKeysDevice* device = componentInstance->device;

    for (int i = 0; i < NumberOfOverridePins; i++) {
        limitOverride |= *componentInstance->motion_override_limit[i];
    }

    if (limitOverride == true && device->PEv2.LimitOverride == 0) {
        device->PEv2.LimitOverrideSetup = 1;
        int ret = PK_PEv2_PulseEngineStateSet(device);
        rtapi_print_msg(RTAPI_MSG_WARN, "Cycle %d, SET LIMIT OVERRIDE TRUE:%d\n", componentInstance->internals->cycles, ret);
    } else if (limitOverride == false && device->PEv2.LimitOverride == 1) {
        device->PEv2.LimitOverrideSetup = 0;
        int ret = PK_PEv2_PulseEngineStateSet(device);
        rtapi_print_msg(RTAPI_MSG_WARN, "Cycle %d, SET LIMIT OVERRIDE FALSE:%d\n", componentInstance->internals->cycles, ret);
    }
}

// ------------------------------------
// Reads the PulseEngine status, checks if an emergency stop has occured.
// Since the PE will not reset when the switch is changed, we switch to stopped and from then on read the raw pin.
// ------------------------------------
void PMC_ProcessEStop(struct ComponentStruct* componentInstance) {
    if (componentInstance->device->PEv2.PulseEngineState == PK_PEState_peSTOP_EMERGENCY) {
        rtapi_print_msg(RTAPI_MSG_ERR, "Cycle %d, E-Stop due to PulseEngine\n", componentInstance->internals->cycles);

        *componentInstance->machine_estop = true;

        PMC_SetPulseEngineStatus(componentInstance, PK_PEState_peSTOPPED, "Set PE stopped due to ESTOP!");
        PMC_SetActiveOutputsOff(componentInstance);
    } else {
		bool currentEstop = 0 + *componentInstance->machine_estop;

        uint8_t eStopPin = componentInstance->device->Pins[EstopPinNumber].DigitalValueGet;
		rtapi_print_msg(RTAPI_MSG_DBG, "Cycle %d, Getting E-Stop:%d\n", componentInstance->internals->cycles, eStopPin);

		if (currentEstop == 1 && eStopPin == 0) {
			rtapi_print_msg(RTAPI_MSG_WARN, "Cycle %d, E-Stop is Reset (by pin)\n", componentInstance->internals->cycles);

			*componentInstance->machine_estop = false;
		} else if (currentEstop == 0 && eStopPin > 0) {
			rtapi_print_msg(RTAPI_MSG_ERR, "Cycle %d, E-Stop due to pin!\n", componentInstance->internals->cycles);

			*componentInstance->machine_estop = true;

            PMC_SetActiveOutputsOff(componentInstance);
		}
    }
}

// ------------------------------------
// Process output and input digital pins.
// ------------------------------------
void PMC_ProcessDigitalPins(struct ComponentStruct* componentInstance) {
    for (int i = 0; i < componentInstance->configuration->output_pins; i++) {
        int pinNumber = componentInstance->configuration->output_pin_map[i];

        uint8_t pinState = *componentInstance->io_output_pin[i];
        componentInstance->device->Pins[pinNumber].DigitalValueSet = pinState;
    }

    int ret = PMC_DigitalIOSetGet(componentInstance);
    //rtapi_print_msg(RTAPI_MSG_DBG, "Cycle %d, Update all digital pins:%d\n", componentInstance->internals->cycles, ret);

    for (int i = 0; i < componentInstance->configuration->input_pins; i++) {
        int pinNumber = componentInstance->configuration->input_pin_map[i];

        uint8_t pinState = componentInstance->device->Pins[pinNumber].DigitalValueGet;

        if (pinState > 0) {
            *componentInstance->io_input_pin[i] = true;
        } else {
            *componentInstance->io_input_pin[i] = false;
        }
    }
}

// ------------------------------------
// Process PWM pins.
// ------------------------------------
void PMC_ProcessPwmPins(struct ComponentStruct* componentInstance) {
    bool setNecessary = false;
    sPoKeysDevice* device = componentInstance->device;

    for (int i = 0; i < componentInstance->configuration->pwm_pins; i++) {
        int channel = componentInstance->configuration->pwm_pin_map[i];
        float pinValue = *componentInstance->io_pwm_pin[i];

        if (pinValue < 0.0f || pinValue > 100.0f) {
            rtapi_print_msg(RTAPI_MSG_ERR, "Cycle %d, PWM channel %d, exceeds range of 0.0 - 100.0!\n", componentInstance->internals->cycles, channel);

            if (device->PWM.PWMduty[channel] > 0) {
                // something wrong, let's stop here.
                device->PWM.PWMduty[channel] = 0;
                setNecessary = true;
            }
        } else if (pinValue == 0.0f && device->PWM.PWMduty[channel] == 0) {
            continue;
        } else {
            uint32_t dutyCycle = ((pinValue / 100.0f) * (float)device->PWM.PWMperiod);

            if (device->PWM.PWMduty[channel] - dutyCycle != 0) {
                rtapi_print_msg(RTAPI_MSG_DBG, "Cycle %d, PWM channel %d, set from %d to %d\n", componentInstance->internals->cycles, channel, device->PWM.PWMduty[channel], dutyCycle);
                device->PWM.PWMduty[channel] = dutyCycle;
                setNecessary = true;
            }
        }
    }

    if (setNecessary) {
        int ret = PK_PWMUpdate(device);
        rtapi_print_msg(RTAPI_MSG_DBG, "Cycle %d, Update PWM:%d\n", componentInstance->internals->cycles, ret);
    }
}

// ------------------------------------
// Process encoders.
// ------------------------------------
void PMC_ProcessEncoders(struct ComponentStruct* componentInstance) {
    component_configuration* config = componentInstance->configuration;
    sPoKeysDevice* device = componentInstance->device;

    for (int i = 0; i < config->encoders; i++) {
		int encoder = config->encoders_map[i];
        int64_t currentValue = device->Encoders[encoder].encoderValue;
        int64_t countDifference = currentValue - *componentInstance->io_encoder_count[i];

        // handle int32 wrap-around
        if (countDifference > INT32_MAX) {
            countDifference += ((int64_t)INT32_MIN*2);
        } else if (countDifference < INT32_MIN) {
            countDifference -= ((int64_t)INT32_MIN*2);
        }

        *componentInstance->io_encoder_count[i] = currentValue;

        uint8_t bufferPosition = componentInstance->internals->encoders_buffer_position[i][0];
        uint8_t averagePosition = componentInstance->internals->encoders_buffer_position[i][1];
        bool bufferFull = false;

        componentInstance->internals->encoders_buffer_values[i][bufferPosition] = countDifference;
        bufferPosition++;

        if (bufferPosition == EncoderLastValues) {
            bufferPosition = 0;
            bufferFull = true;
        }

        componentInstance->internals->encoders_buffer_position[i][0] = bufferPosition;

        int32_t sumDifference = 0;
        for (int j = 0; j < EncoderLastValues; j++) {
            sumDifference += componentInstance->internals->encoders_buffer_values[i][j];
        }

        componentInstance->internals->encoders_buffer_values[i][EncoderLastValues + averagePosition] = sumDifference;

        if (bufferFull == true) {
            averagePosition++;

            if (averagePosition == EncoderLastAverages) {
                averagePosition = 0;
            }

            componentInstance->internals->encoders_buffer_position[i][1] = averagePosition;
        }

        float sumAverages = 0;
        for (int j = 0; j < EncoderLastAverages; j++) {
            sumAverages += componentInstance->internals->encoders_buffer_values[i][EncoderLastValues + j] / (float)EncoderLastValues;
        }

        float avg = (sumAverages / EncoderLastAverages) * 200; // 200 = 1'000ms / 5ms Cycle time

        *componentInstance->io_encoder_cps[i] = avg;
        *componentInstance->io_encoder_vps[i] = avg / config->encoders_scale[i];

        int8_t indexPinConfig = config->encoders_index_pin[i];

        if (indexPinConfig > NoEncoderIndex) {
            uint8_t pinState = device->Pins[abs(indexPinConfig)].DigitalValueGet;

            if ((pinState > 0 && indexPinConfig >= 0) || (pinState == 0 && indexPinConfig < 0)) {
                *componentInstance->io_encoder_index[i] = true;
            } else {
                *componentInstance->io_encoder_index[i] = false;
            }
        }
    }
}

// ------------------------------------
// Checks whether there is motion being streamed.
// ------------------------------------
bool PMC_StreamAvailable(struct ComponentStruct* componentInstance) {
    hal_stream_t stream;
    int ret = hal_stream_attach(&stream, comp_id, SharedMemoryKey, componentInstance->configuration->streamtype);

    if (ret < 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "Cycle %d, Shared Buffer error: %d\n", componentInstance->internals->cycles, ret);
        return false;
    }

    bool readable = hal_stream_readable(&stream);
    hal_stream_detach(&stream);
    return readable;
}

// ------------------------------------
// If the motion was interrupted, there may still be data in the buffer.
// Read and discard the buffer until we get the EOM signal.
// ------------------------------------
bool PMC_FinishStream(struct ComponentStruct* componentInstance) {
    hal_stream_t stream;
    int ret = hal_stream_attach(&stream, comp_id, SharedMemoryKey, componentInstance->configuration->streamtype);

    if (ret < 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "Cycle %d, Finishing stream, error attaching: %d\n", componentInstance->internals->cycles, ret);
        return true;
    }

    bool readable = hal_stream_readable(&stream);

    uint8_t numberOfAxes = componentInstance->configuration->number_axes;
    while (readable) {
        union hal_stream_data dataToReceive[numberOfAxes];
        ret = hal_stream_read(&stream, dataToReceive, NULL);

        if (ret != 0) {
            rtapi_print_msg(RTAPI_MSG_ERR, "Cycle %d, Finishing stream, error reading: %d\n", componentInstance->internals->cycles, ret);
            break;
        }

        if (dataToReceive[0].s == EndOfMotionPacket) {
            // rtapi_print_msg(RTAPI_MSG_DBG, "Cycle %d, Finishing stream, end of motion received\n", componentInstance->internals->cycles);
            hal_stream_detach(&stream);
            return true;
        }

        readable = hal_stream_readable(&stream);
    }

    hal_stream_detach(&stream);
    return false;
}

// ------------------------------------
// Process streamed move command and implicitly update PE status information.
// Returns false when movement stops.
// ------------------------------------
enum State PMC_ProcessMoveCommand(struct ComponentStruct* componentInstance) {
    enum State nextState = MOVING;
    hal_stream_t stream;
    int ret = hal_stream_attach(&stream, comp_id, SharedMemoryKey, componentInstance->configuration->streamtype);

    if (ret < 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "Cycle %d, Shared Buffer error: %d\n", componentInstance->internals->cycles, ret);
        return MOTIONERROR;
    }

    bool streamReadable = hal_stream_readable(&stream);

    if (!streamReadable) {
        // if the last cycle was slow (>5ms), we do not wait and "almost immediately" process the next motion state.
        // since the servo thread may not have updated yet, we delay here to get at least one value here.
        rtapi_print_msg(RTAPI_MSG_WARN, "Cycle %d, Potential Buffer underrun? EndOfMotion Packet missing? Try sleep\n", componentInstance->internals->cycles);
        usleep(1000); // the time of the servo period (1ms).
        streamReadable = hal_stream_readable(&stream);
    }

    if (streamReadable) {
        sPoKeysDevice* device = componentInstance->device;
        device->PEv2.motionBufferEntriesAccepted = 0;
        device->PEv2.newMotionBufferEntries = 0;

        int motionEntries = 0;
        uint8_t numberOfAxes = componentInstance->configuration->number_axes;
        uint8_t maxMotionPackets = componentInstance->configuration->max_motion_packets;

        do
        {
            union hal_stream_data dataToReceive[numberOfAxes];

            ret = hal_stream_read(&stream, dataToReceive, NULL);

            if (ret != 0) {
                rtapi_print_msg(RTAPI_MSG_ERR, "Cycle %d, Error reading stream: %d\n", componentInstance->internals->cycles, ret);
                nextState = MOTIONERROR;
                break;
            }

            if (dataToReceive[0].s == EndOfMotionPacket) {
                rtapi_print_msg(RTAPI_MSG_INFO, "Cycle %d, End of motion received\n", componentInstance->internals->cycles);
                nextState = ENABLED;
                streamReadable = false;
            } else {
                //rtapi_print_msg(RTAPI_MSG_INFO, "Cycle %d, Pulses: ", componentInstance->internals->cycles);

                for (int i = 0; i < numberOfAxes; i++) {
                    if (dataToReceive[i].s > 256) {
                        rtapi_print_msg(RTAPI_MSG_ERR, "Cycle %d, Motion commanded exceeds limit: %d\n", componentInstance->internals->cycles, dataToReceive[i].s);
                        nextState = MOTIONERROR;
                        hal_stream_detach(&stream);
                        return nextState;
                    }

                    uint8_t motion = dataToReceive[i].s;
                    //rtapi_print_msg(RTAPI_MSG_INFO, "%d,", motion);
                    device->PEv2.MotionBuffer[(motionEntries * numberOfAxes) + i] = motion;
                }

                //rtapi_print_msg(RTAPI_MSG_INFO, "\n");

                motionEntries++;

                streamReadable = hal_stream_readable(&stream);
            }

            if (streamReadable == false || motionEntries == maxMotionPackets) {
                device->PEv2.newMotionBufferEntries = motionEntries;

                ret = PK_PEv2_BufferFill(device);

                if (device->PEv2.motionBufferEntriesAccepted != motionEntries) {
                    rtapi_print_msg(RTAPI_MSG_ERR, "Cycle %d, PE Axes not all buffer entries accepted (%d, accepted %d) %d\n", componentInstance->internals->cycles, motionEntries, device->PEv2.motionBufferEntriesAccepted, ret);
                    nextState = MOTIONERROR;
                    hal_stream_detach(&stream);
                    return nextState;
                }

                motionEntries = 0;
                //rtapi_print_msg(RTAPI_MSG_DBG, "Cycle %d, PE Axes (%d, accepted %d), Move commanded:%d\n", componentInstance->internals->cycles, motionEntries, device->PEv2.motionBufferEntriesAccepted, ret);
            }
        }
        while (streamReadable);
    } else {
        rtapi_print_msg(RTAPI_MSG_ERR, "Cycle %d, Buffer underrun? EndOfMotion Packet missing?\n", componentInstance->internals->cycles);
        nextState = MOTIONERROR;
    }

    hal_stream_detach(&stream);

    return nextState;
}

// ------------------------------------
// Updates the HAL pins based on the current PE position information.
// ------------------------------------
void PMC_ProcessPositions(struct ComponentStruct* componentInstance) {
    sPoKeysDevice* device = componentInstance->device;

    for (int i = 0; i < componentInstance->configuration->number_axes; i++) {
        *componentInstance->axis_position_feedback[i] = ((float)device->PEv2.CurrentPosition[i]) / ((float)componentInstance->axis_step_scale[i]);
        *componentInstance->axis_limit_positive[i] = (device->PEv2.LimitStatusP >> i) & 0x01;
        *componentInstance->axis_limit_negative[i] = (device->PEv2.LimitStatusN >> i) & 0x01;
        *componentInstance->axis_home[i] = (device->PEv2.HomeStatus >> i) & 0x01;

        //rtapi_print_msg(RTAPI_MSG_DBG, "Axis %d: %fmm, P%d, N%d, H%d", i, *componentInstance->axis_position_feedback[i], *componentInstance->axis_limit_positive[i], *componentInstance->axis_limit_negative[i], *componentInstance->axis_home[i]);
    }

    //rtapi_print_msg(RTAPI_MSG_DBG, "\n");
}

// ------------------------------------
// Process relays on/off
// ------------------------------------
void PMC_ProcessRelays(struct ComponentStruct* componentInstance) {
    sPoKeysDevice* device = componentInstance->device;

    int ret = PK_PEv2_ExternalOutputsGet(device);
    //rtapi_print_msg(RTAPI_MSG_DBG, "Cycle %d, Getting Relay status:%d, %d\n", componentInstance->internals->cycles, ret, device->PEv2.ExternalOCOutputs);

    bool ssr1on = 0 + *componentInstance->io_solid_state_relay[0];
    bool ssr2on = 0 + *componentInstance->io_solid_state_relay[1];
    bool relay1on = 0 + *componentInstance->io_relay[0];
    bool relay2on = 0 + *componentInstance->io_relay[1];
    bool oc1on = 0 + *componentInstance->io_open_collector[0];
    bool oc2on = 0 + *componentInstance->io_open_collector[1];
    bool oc3on = 0 + *componentInstance->io_open_collector[2];
    bool oc4on = 0 + *componentInstance->io_open_collector[3];

    bool setNecessary = false;
    setNecessary |= PMC_CompareRelayState(device, ssr1on, 7);
    setNecessary |= PMC_CompareRelayState(device, ssr2on, 0);
    setNecessary |= PMC_CompareRelayState(device, relay1on, 2);
    setNecessary |= PMC_CompareRelayState(device, relay2on, 1);
    setNecessary |= PMC_CompareRelayState(device, oc1on, 3);
    setNecessary |= PMC_CompareRelayState(device, oc2on, 4);
    setNecessary |= PMC_CompareRelayState(device, oc3on, 5);
    setNecessary |= PMC_CompareRelayState(device, oc4on, 6);

    if (setNecessary) {
        ret = PK_PEv2_ExternalOutputsSet(device);
        rtapi_print_msg(RTAPI_MSG_INFO, "Cycle %d, Change relays:%d\n", componentInstance->internals->cycles, ret);
    }
}

// ------------------------------------
// Compare actual relay state to expected state.
// On Pokeys57CNC the outputs are all accessed using ExternalOCOutputs! 0=SSR2, 7=SSR1, etc. See protocol definition.
// ------------------------------------
inline bool PMC_CompareRelayState(sPoKeysDevice* device, bool state, int offset) {
    if (state == true && ((device->PEv2.ExternalOCOutputs >> offset) & 0x01) == 0) {
        device->PEv2.ExternalOCOutputs |= (1 << offset);
        return true;
    } else if (state == false && ((device->PEv2.ExternalOCOutputs >> offset) & 0x01) == 1) {
        device->PEv2.ExternalOCOutputs &= (0 << offset);
        return true;
    }

    return false;
}

// ------------------------------------
// Set all relays and PWM outputs off.
// ------------------------------------
void PMC_SetActiveOutputsOff(struct ComponentStruct* componentInstance) {
    sPoKeysDevice* device = componentInstance->device;

    if (device->PEv2.ExternalOCOutputs > 0) {
        device->PEv2.ExternalOCOutputs = 0;
        int ret = PK_PEv2_ExternalOutputsSet(device);
        rtapi_print_msg(RTAPI_MSG_WARN, "Turn all relays off:%d\n", ret);
    }

    bool setNecessary = false;
    for (int i = 0; i < 6; i++) {
        if (device->PWM.PWMduty[i] > 0) {
            device->PWM.PWMduty[i] = 0;
            setNecessary = true;
        }
    }

    if (setNecessary) {
        int ret = PK_PWMUpdate(device);
        rtapi_print_msg(RTAPI_MSG_WARN, "Turn PWM off:%d\n", ret);
    }
}

// ------------------------------------
// Get the current timestamp. Consumer must free the memory of the timestamp!
// ------------------------------------
struct timespec* PMC_GetStartTime() {
    struct timespec* timeStamp;
    timeStamp = malloc(sizeof(struct timespec));
    clock_gettime(CLOCK_REALTIME, timeStamp);

    return timeStamp;
}

// ------------------------------------
// Try to keep the cycle time within defined limits.
// ------------------------------------
void PMC_ProcessCycleTime(struct timespec* cycleStart, bool overrideCycleTime, enum State currentState, struct ComponentStruct* componentInstance) {
    enum State nextState = componentInstance->internal_state;
    struct timespec cycleEnd;
    clock_gettime(CLOCK_REALTIME, &cycleEnd);
    float cycleTimeMs = ((float)(cycleEnd.tv_sec - cycleStart->tv_sec) * 1.0e9 + (float)(cycleEnd.tv_nsec - cycleStart->tv_nsec)) / 1.0e6;
    free(cycleStart);

    rtapi_print_msg(RTAPI_MSG_DBG, "Cycle %d, Time elapsed %0.2f ms\n", componentInstance->internals->cycles, cycleTimeMs);

    if (currentState != nextState) {
        const char* currentStateName = PMC_GetStateName(currentState);
        const char* nextStateName = PMC_GetStateName(nextState);

        rtapi_print_msg(RTAPI_MSG_DBG, "Cycle %d, Change state from %s to %s\n", componentInstance->internals->cycles, currentStateName, nextStateName);
    }

    if (!overrideCycleTime) {
        if (cycleTimeMs <= CycleTimeMs) {
            useconds_t sleepTimeUs = (CycleTimeMs - cycleTimeMs) * 1000;
            usleep(sleepTimeUs);
        } else {
            const char* currentStateName = PMC_GetStateName(currentState);
            const char* nextStateName = PMC_GetStateName(nextState);

            if (cycleTimeMs <= CycleTimeMs + 3.0) {
                rtapi_print_msg(RTAPI_MSG_WARN, "Cycle %d, Greater than %0.1fms elapsed %0.2fms, from %s to %s\n", componentInstance->internals->cycles, CycleTimeMs, cycleTimeMs, currentStateName, nextStateName);
            } else {
                rtapi_print_msg(RTAPI_MSG_ERR, "Cycle %d, Greater than %0.1fms! elapsed %0.2fms, from %s to %s\n", componentInstance->internals->cycles, CycleTimeMs, cycleTimeMs, currentStateName, nextStateName);
            }
        }
    }

    componentInstance->internals->cycles++;
}

// ------------------------------------
// Helper method to get the state enum name.
// ------------------------------------
inline const char* PMC_GetStateName(enum State state) {
    switch (state) {
        case SHUTDOWN: return "SHUTDOWN";
        case INIT: return "INIT";
        case IDLE: return "IDLE";
        case ENABLED: return "ENABLED";
        case MOTIONBUFFERING: return "MOTIONBUFFERING";
        case MOVING: return "MOVING";
        case MOTIONERROR: return "MOTIONERROR";
        case MOTIONDISABLE: return "MOTIONDISABLE";
        case MOTIONESTOP: return "MOTIONESTOP";
        case ESTOP: return "ESTOP";
        default: return "UNDEFINED";
    }
}

// ------------------------------------
// Extension of method `PK_DigitalIOSetGet`.
// With addition of reading and handling encoder counts.
// PoKeysLib updates encoders with a separate method "PK_EncoderValuesGet", which uses separate requests.
// ------------------------------------
int32_t PMC_DigitalIOSetGet(struct ComponentStruct* componentInstance) {
    sPoKeysDevice* device = componentInstance->device;
    int ret = PK_DigitalIOSetGet(device);

    if (ret == PK_OK) {
        component_configuration* config = componentInstance->configuration;
        component_internals* internals = componentInstance->internals;
        for (int i = 0; i < config->encoders; i++) {
            int encoder = config->encoders_map[i];

            if (encoder == UfEncoder) {
                // Ultra fast encoder delivers an absolute value
                device->Encoders[UfEncoder].encoderValue = *((int32_t*)&device->response[58]);
                continue;
            }

            int8_t previousValue = internals->encoders_value_previous[i];
            int8_t currentValue = device->response[25 + encoder];
            int16_t difference = currentValue - previousValue;

			// handle byte wrap-around
            if (difference > 127) {
                difference -= 255;
            } else if (difference < -127) {
                difference += 255;
            }

            internals->encoders_value_previous[i] = currentValue;
            device->Encoders[encoder].encoderValue += difference;
        }
    }

	return ret;
}
