component PoKeysMotionBuffer;

pin in bit component_is_ready = false "Only when the receiving component is ready, motion should be streamed";

pin in bit motion.is_enabled = false "When the motion planner is enabled, motion can happen. Conversely if disabled motion mus stop immediately.";
pin in bit motion.in_position = true "When the motion planner is not in position, start streaming the commanded position";
pin in bit motion.jog_is_active = false "When the motion planner is jogging, \"in position\" remains true, start streaming the commanded position";

pin out bit motion.is_init = false "Flag whether the internal position is synchronised with the input pins (DEBUG)";
pin out bit motion.is_streaming = false "Flag whether the motion is being streamed (DEBUG)";
pin out bit motion.has_error = false "Indicates that the stream had an error. Prevents spamming from RT thread, only show error once (DEBUG)";

pin in float axis.#.position_command [8 : personality] "Commanded position by the motion controller";
pin out float axis.#.last_position [8 : personality] "Internal tracking of last commanded position (DEBUG)";
pin out float axis.#.pulses_leftover [8 : personality] "Internal tracking of partial pulses (DEBUG)";

param rw float axis.#.step_scale [8 : personality] "1 machine unit equals x pulses";
param r float axis.#.step_width [8 : personality] "1 pulse equals x units (DEBUG)";

function _;
option userspace no;
option extra_setup yes;
option extra_cleanup yes;

license "GPL"; // indicates GPL v2 or later
author "T.Frei";
;;
#include <rtapi_math.h>     // for "fabs"
#include <stdlib.h>         // for "abs"

#define SharedMemoryKey 57       // Arbitrary number
#define BufferDepth 128          // Buffer on PoKeys side would be 128
#define EndOfMotionPacket 0x0101 // Arbitrary number > uint8
//#define MeasureTime            // Debug information how long the methods take

hal_stream_t* MotionStream;      // Streaming exchange to the uspace component

// ------------------------------------
// Setup function
// ------------------------------------
EXTRA_SETUP() {
#ifdef MeasureTime
    long long startTime = rtapi_get_time();
#endif

    MotionStream = hal_malloc(sizeof(hal_stream_t));

    char streamType[personality + 1];
    for (int i=0; i < personality; i++) {
        streamType[i] = 'S';
    }
    streamType[personality] = 0; // null terminate manually

    int ret = hal_stream_create(MotionStream, comp_id, SharedMemoryKey, BufferDepth, streamType);
    int exitCode = 0;

    if(ret < 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "Failed to create stream: %d\n", ret);
        hal_exit(comp_id);

        exitCode = ret;
    } else {
        //rtapi_print_msg(RTAPI_MSG_DBG, "Created stream: %d\n", ret);
    }

#ifdef MeasureTime
    long long endTime = rtapi_get_time();
    long int deltaTime = (long int)(endTime - startTime) / 1000;
    rtapi_print_msg(RTAPI_MSG_DBG, "BUFFER SETUP took: %dus\n", deltaTime);
#endif

    return exitCode;
}

// ------------------------------------
// Cleanup function
// ------------------------------------
EXTRA_CLEANUP() {
#ifdef MeasureTime
    long long startTime = rtapi_get_time();
#endif

	//rtapi_print_msg(RTAPI_MSG_DBG, "Buffer cleanup stream\n");
    hal_stream_detach(MotionStream);
    free(MotionStream);

#ifdef MeasureTime
    long long endTime = rtapi_get_time();
    long int deltaTime = (long int)(endTime - startTime) / 1000;
    rtapi_print_msg(RTAPI_MSG_DBG, "BUFFER CLEANUP took: %dus\n", deltaTime);
#endif
}

// ------------------------------------
// Main Function
// ------------------------------------
FUNCTION(_) {
    // if either the motion planner or the controller component is inactive we must immediately stop and idle.
    if (!(motion_is_enabled && component_is_ready)) {
        if (motion_is_streaming) {
            union hal_stream_data dataToSend[personality];
            dataToSend[0].s = EndOfMotionPacket;
            int writeRes = hal_stream_write(MotionStream, dataToSend);

            if (writeRes != 0 && motion_has_error == false) {
                rtapi_print_msg(RTAPI_MSG_ERR, "End of Motion BUFFER overrun: %d\n", writeRes);
            }

            motion_has_error = false;
            motion_is_streaming = false;
        }

        if (motion_is_init) {
            motion_is_init = false;
        }

        return;
    }

    if (!motion_is_init) {
        for (int i = 0; i < personality; i++) {
            axis_last_position(i) = axis_position_command(i);
            axis_pulses_leftover(i) = 0.0f;
            axis_step_width(i) = 1 / fabs(axis_step_scale(i));
        }

        motion_is_init = true;
    }

    // if either we are not in position or jogging is active we must start streaming.
    // if neither applies, but we were streaming, check if we have reached the final commanded position.
    bool motionCommanded = false;
    if (motion_in_position == false || motion_jog_is_active == true) {
        motionCommanded = true;
    } else if (motion_is_streaming) {
        for (int i = 0; i < personality; i++) {
            float differenceInPosition = axis_position_command(i) - axis_last_position(i);

            if (fabs(differenceInPosition) >= axis_step_width(i)) {
                motionCommanded = true;
                break;
            }
        }
    }

	if (motionCommanded) {
#ifdef MeasureTime
        long long startTime = rtapi_get_time();
#endif
        union hal_stream_data dataToSend[personality];

        for (int i = 0; i < personality; i++) {
            float differenceInPosition = axis_position_command(i) - axis_last_position(i);

            if (fabs(differenceInPosition) < axis_step_width(i)) {
                dataToSend[i].s = 0;
            } else {
                axis_last_position(i) = axis_position_command(i);

                float pulsesDifference = differenceInPosition * axis_step_scale(i);
                int32_t pulses = floor(pulsesDifference);
                axis_pulses_leftover(i) += (pulsesDifference - pulses);

                if (axis_pulses_leftover(i) >= 1.0f) {
                    pulses++;
                    axis_pulses_leftover(i) -= 1.0f;
                }
                else if (axis_pulses_leftover(i) <= -1.0f) {
                    pulses--;
                    axis_pulses_leftover(i) += 1.0f;
                }

                int32_t motion = abs(pulses) & 127;

                if (pulses < 0) {
                    motion |= (1<<7);
                }

                dataToSend[i].s = motion;
            }
        }

        int writeRes = hal_stream_write(MotionStream, dataToSend);
        if (writeRes != 0 && motion_has_error == false) {
            rtapi_print_msg(RTAPI_MSG_ERR, "BUFFER overrun: %d\n", writeRes);
            motion_has_error = true;
        }

        motion_is_streaming = true;

#ifdef MeasureTime
        long long endTime = rtapi_get_time();
        long int deltaTime = (long int)(endTime - startTime) / 1000;

        if (deltaTime >= 50) {
            rtapi_print_msg(RTAPI_MSG_WARN, "BUFFER SEND took: %dus\n", deltaTime);
        }
#endif

        return;
	}

    if (motion_is_streaming) {
        motion_is_streaming = false;

        union hal_stream_data dataToSend[personality];
        dataToSend[0].s = EndOfMotionPacket;
        int writeRes = hal_stream_write(MotionStream, dataToSend);

        if (writeRes != 0 && motion_has_error == false) {
            rtapi_print_msg(RTAPI_MSG_ERR, "End of Motion BUFFER overrun: %d\n", writeRes);
        }

        // reset stream error at the end of one motion.
        motion_has_error = false;
    }
}
