/* Autogenerated by /usr/bin/halcompile on Sun Nov 16 11:43:33 2025 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:PoKeysHoming:");
MODULE_INFO(linuxcnc, "pin:request:s32:0:in::0:None");
MODULE_INFO(linuxcnc, "pin:response:s32:0:out::0:None");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_INFO(linuxcnc, "author:T.Frei");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_s32_t *request;
    hal_s32_t *response;
};
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_s32_newf(HAL_IN, &(inst->request), comp_id,
        "%s.request", prefix);
    if(r != 0) return r;
    *(inst->request) = 0;
    r = hal_pin_s32_newf(HAL_OUT, &(inst->response), comp_id,
        "%s.response", prefix);
    if(r != 0) return r;
    *(inst->response) = 0;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
int rtapi_app_main(void) {
    int r = 0;
    comp_id = hal_init("PoKeysHoming");
    if(comp_id < 0) return comp_id;
    r = export("PoKeysHoming", 0);
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef request
#define request (0+*__comp_inst->request)
#undef response
#define response (*__comp_inst->response)


#line 12 "./source/PoKeysHoming.comp"
//#include <homing.c>

static emcmot_joint_t  *joints;

// data for per-joint homing-specific hal pins:
typedef struct {
    hal_bit_t *home_sw;      // home switch input
    hal_bit_t *homing;       // joint is homing
    hal_bit_t *homed;        // joint was homed
    hal_bit_t *index_enable; // motmod sets: request reset on index
                             //        encoder clears: index arrived
    hal_s32_t *home_state;   // homing state machine state
} one_joint_home_data_t;

typedef struct {
    one_joint_home_data_t jhd[EMCMOT_MAX_JOINTS];
} all_joints_home_data_t;

static all_joints_home_data_t *joint_home_data = 0;

static int makepins(int id, int njoints) {
    // home_pins needed to work with configs expecting them:
    int jno;
    int retval;
    one_joint_home_data_t *addr;

    joint_home_data = hal_malloc(sizeof(all_joints_home_data_t));
    if (joint_home_data == 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "HOMING: all_joints_home_data_t malloc failed\n");
        return -1;
    }

    retval = 0;
    for (jno = 0; jno < njoints; jno++) {
        addr = &(joint_home_data->jhd[jno]);

        retval += hal_pin_bit_newf(HAL_IN, &(addr->home_sw), id, "joint.%d.home-sw-in", jno);
        retval += hal_pin_bit_newf(HAL_OUT, &(addr->homing), id, "joint.%d.homing", jno);
        retval += hal_pin_bit_newf(HAL_OUT, &(addr->homed), id, "joint.%d.homed", jno);
        retval += hal_pin_s32_newf(HAL_OUT, &(addr->home_state), id, "joint.%d.home-state", jno);
        retval += hal_pin_bit_newf(HAL_IO, &(addr->index_enable), id, "joint.%d.index-enable", jno);
    }

    return retval;
}

// All (skeleton) functions required for homing api follow:
void homeMotFunctions(void(*pSetRotaryUnlock)(int,int), int (*pGetRotaryIsUnlocked)(int)) {
    (void)pSetRotaryUnlock;
    (void)pGetRotaryIsUnlocked;
    return;
}

int homing_init(int id,
                double servo_period,
                int n_joints,
                int n_extrajoints,
                emcmot_joint_t* pjoints) {
    (void)servo_period;
    (void)n_extrajoints;
    joints = pjoints;
    return makepins(id,n_joints);
}

bool do_homing(void) {
    return true;
}

bool get_allhomed() {
    return true;
}

bool get_homed(int jno) {
    (void)jno;
    return true;
}

bool get_home_is_idle(int jno) {
    (void)jno;
    return true;
}

bool get_home_is_synchronized(int jno) {
    (void)jno;
    return false;
}

bool get_home_needs_unlock_first(int jno) {
    (void)jno;
    return false;
}

int  get_home_sequence(int jno) {
    (void)jno;
    return 0;
}

bool get_homing(int jno) {
    (void)jno;
    return false;
}

bool get_homing_at_index_search_wait(int jno) {
    (void)jno;
    return false;
}

bool get_homing_is_active() {
    return false;
}

bool get_index_enable(int jno) {
    (void)jno;
    return false;
}

void read_homing_in_pins(int njoints) {
    (void)njoints;
    return;
}

void do_home_joint(int jno) {
    (void)jno;
    return;
}

void set_unhomed(int jno, motion_state_t motstate) {
    (void)jno;
    (void)motstate;
    return;
}

void do_cancel_homing(int jno) {
    (void)jno;
    return;
}

void set_joint_homing_params(int    jno,
                             double offset,
                             double home,
                             double home_final_vel,
                             double home_search_vel,
                             double home_latch_vel,
                             int    home_flags,
                             int    home_sequence,
                             bool   volatile_home
                             ) {
    (void)jno;
    (void)offset;
    (void)home;
    (void)home_final_vel;
    (void)home_search_vel;
    (void)home_latch_vel;
    (void)home_flags;
    (void)home_sequence;
    (void)volatile_home;
    return;
}

void update_joint_homing_params (int    jno,
                                 double offset,
                                 double home,
                                 int    home_sequence
                                ) {
    (void)jno;
    (void)offset;
    (void)home;
    (void)home_sequence;
    return;
}

void write_homing_out_pins(int njoints) {
    (void)njoints;
    return;
}

static int __comp_get_data_size(void) { return 0; }
